import { SchematicPreset } from '../../../types/schematic';

export const SCHEMATIC_PRESETS: SchematicPreset[] = [
  {
    id: 'preset_danfoss_basic',
    name: 'Ciclo Básico Danfoss (5 Componentes)',
    description: 'Esquema básico fundamental del circuito frigorífico según Danfoss: Compresor, Condensador, Recipiente de líquido, Válvula de expansión y Evaporador.',
    category: 'Básico Danfoss',
    refrigerant: 'R134a',
    iconName: 'Activity',
    nodes: [
      {
        id: 'comp-danfoss',
        type: 'schematicNode',
        position: { x: 460, y: 80 },
        data: {
          componentType: 'compressor_reciprocating',
          label: 'Compresor',
          tag: 'CMP-01',
          modelNumber: 'Danfoss Maneurop MTZ',
          powerKw: 5.5,
          displacementM3h: 14.8,
          pressureInBar: 2.0,
          pressureOutBar: 11.5,
          tempInC: 10.0,
          tempOutC: 72.0,
          isEnergized: true,
        },
      },
      {
        id: 'cond-danfoss',
        type: 'schematicNode',
        position: { x: 740, y: 180 },
        data: {
          componentType: 'condenser_air',
          label: 'Condensador',
          tag: 'COND-01',
          modelNumber: 'Danfoss Optyma Condenser',
          capacityKw: 18.0,
          setpointTempC: 42.0,
          subcoolingK: 4.0,
        },
      },
      {
        id: 'rec-danfoss',
        type: 'schematicNode',
        position: { x: 740, y: 440 },
        data: {
          componentType: 'liquid_receiver_vertical',
          label: 'Recipiente',
          tag: 'REC-01',
          modelNumber: 'Danfoss Receiver 15L',
          volumeL: 15.0,
          pressureOutBar: 11.2,
        },
      },
      {
        id: 'txv-danfoss',
        type: 'schematicNode',
        position: { x: 260, y: 440 },
        data: {
          componentType: 'expansion_valve_txv',
          label: 'Válvula de expansión',
          tag: 'TXV-01',
          modelNumber: 'Danfoss TE2 / T2 R134a',
          capacityKw: 12.0,
          superheatK: 5.0,
        },
      },
      {
        id: 'evap-danfoss',
        type: 'schematicNode',
        position: { x: 120, y: 180 },
        data: {
          componentType: 'evaporator_dx_air',
          label: 'Evaporador',
          tag: 'EVAP-01',
          modelNumber: 'Danfoss DX Evaporator',
          capacityKw: 12.5,
          setpointTempC: -5.0,
          superheatK: 6.0,
        },
      },
    ],
    edges: [
      // 1. Descarga Compresor -> Condensador (Rojo)
      {
        id: 'e-danfoss-descarga',
        source: 'comp-danfoss',
        sourceHandle: 'discharge',
        target: 'cond-danfoss',
        targetHandle: 'gas_in',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'discharge_superheated',
          customLabel: 'Línea de Descarga HP',
          diameterInch: '3/4"',
          pressureBar: 11.5,
          temperatureC: 72.0,
        },
      },
      // 2. Condensado Condensador -> Recipiente (Amarillo-Naranja)
      {
        id: 'e-danfoss-condensado',
        source: 'cond-danfoss',
        sourceHandle: 'liquid_out',
        target: 'rec-danfoss',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'condensing_liquid',
          customLabel: 'Líquido Condensado',
          diameterInch: '1/2"',
          pressureBar: 11.2,
          temperatureC: 40.0,
        },
      },
      // 3. Líquido Recipiente -> Válvula de Expansión (Amarillo)
      {
        id: 'e-danfoss-liquido',
        source: 'rec-danfoss',
        sourceHandle: 'outlet',
        target: 'txv-danfoss',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'subcooled_liquid',
          customLabel: 'Línea de Líquido',
          diameterInch: '1/2"',
          pressureBar: 11.0,
          temperatureC: 36.0,
        },
      },
      // 4. Expansión Válvula -> Evaporador (Azul Claro)
      {
        id: 'e-danfoss-expansion',
        source: 'txv-danfoss',
        sourceHandle: 'outlet',
        target: 'evap-danfoss',
        targetHandle: 'liquid_in',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'two_phase_flashing',
          customLabel: 'Mezcla Bifásica Fría (LP)',
          diameterInch: '1/2"',
          pressureBar: 2.0,
          temperatureC: -5.0,
        },
      },
      // 5. Aspiración Evaporador -> Compresor (Azul Cobalto)
      {
        id: 'e-danfoss-aspiracion',
        source: 'evap-danfoss',
        sourceHandle: 'gas_out',
        target: 'comp-danfoss',
        targetHandle: 'suction',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'suction_superheated',
          customLabel: 'Línea de Aspiración (LP)',
          diameterInch: '7/8"',
          pressureBar: 2.0,
          temperatureC: 10.0,
        },
      },
    ],
  },
  {
    id: 'preset_standard_dx',
    name: 'Ciclo Simple DX con Recipiente y Acumulador',
    description: 'Instalación clásica de expansión directa con compresor, condensador, recipiente, filtro, visor, TXV y acumulador de aspiración.',
    category: 'Estándar',
    refrigerant: 'R134a',
    iconName: 'Activity',
    nodes: [
      {
        id: 'comp-1',
        type: 'schematicNode',
        position: { x: 440, y: 360 },
        data: {
          componentType: 'compressor_scroll',
          label: 'Compresor Scroll Principal',
          tag: 'CMP-01',
          modelNumber: 'Copeland ZB45KCE',
          powerKw: 7.5,
          displacementM3h: 17.2,
          pressureInBar: 2.0,
          pressureOutBar: 10.5,
          tempInC: -5.0,
          tempOutC: 65.0,
          isEnergized: true,
        },
      },
      {
        id: 'cond-1',
        type: 'schematicNode',
        position: { x: 660, y: 100 },
        data: {
          componentType: 'condenser_air',
          label: 'Condensador por Aire',
          tag: 'COND-01',
          modelNumber: 'Guentner S-GVH',
          capacityKw: 24.5,
          setpointTempC: 40.0,
          subcoolingK: 5.0,
        },
      },
      {
        id: 'rec-1',
        type: 'schematicNode',
        position: { x: 860, y: 200 },
        data: {
          componentType: 'liquid_receiver_vertical',
          label: 'Recipiente de Líquido',
          tag: 'REC-01',
          volumeL: 20.0,
          pressureOutBar: 10.2,
        },
      },
      {
        id: 'filter-1',
        type: 'schematicNode',
        position: { x: 860, y: 360 },
        data: {
          componentType: 'filter_drier',
          label: 'Filtro Deshidratador',
          tag: 'FLT-01',
          modelNumber: 'Danfoss DML 163',
        },
      },
      {
        id: 'sight-1',
        type: 'schematicNode',
        position: { x: 860, y: 460 },
        data: {
          componentType: 'sight_glass',
          label: 'Visor de Líquido y Humedad',
          tag: 'SGT-01',
          modelNumber: 'Danfoss SGI 1/2"',
        },
      },
      {
        id: 'txv-1',
        type: 'schematicNode',
        position: { x: 660, y: 560 },
        data: {
          componentType: 'expansion_valve_txv',
          label: 'Válvula Expansión TXV',
          tag: 'TXV-01',
          modelNumber: 'Danfoss TE2 R134a',
          capacityKw: 15.0,
          superheatK: 5.0,
        },
      },
      {
        id: 'evap-1',
        type: 'schematicNode',
        position: { x: 400, y: 560 },
        data: {
          componentType: 'evaporator_dx_air',
          label: 'Evaporador Frigorífico DX',
          tag: 'EVAP-01',
          modelNumber: 'Lu-Ve F35HC',
          capacityKw: 14.2,
          setpointTempC: -10.0,
          superheatK: 6.0,
        },
      },
      {
        id: 'acc-1',
        type: 'schematicNode',
        position: { x: 220, y: 380 },
        data: {
          componentType: 'suction_accumulator',
          label: 'Acumulador de Succión',
          tag: 'ACC-01',
          volumeL: 12.0,
        },
      },
      {
        id: 'gauge-hp',
        type: 'schematicNode',
        position: { x: 560, y: 240 },
        data: {
          componentType: 'gauge_pressure_hp',
          label: 'Manómetro Descarga HP',
          tag: 'PI-HP',
          measuredValue: 10.5,
          measuredUnit: 'bar',
        },
      },
      {
        id: 'gauge-lp',
        type: 'schematicNode',
        position: { x: 320, y: 260 },
        data: {
          componentType: 'gauge_pressure_lp',
          label: 'Manómetro Aspiración LP',
          tag: 'PI-LP',
          measuredValue: 2.0,
          measuredUnit: 'bar',
        },
      },
    ],
    edges: [
      // Descarga: Compresor -> Condensador
      {
        id: 'e-cmp-cond',
        source: 'comp-1',
        sourceHandle: 'discharge',
        target: 'cond-1',
        targetHandle: 'gas_in',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'discharge_superheated',
          customLabel: 'Línea de Descarga HP',
          diameterInch: '7/8"',
          pressureBar: 10.5,
          temperatureC: 65.0,
        },
      },
      // Condensado: Condensador -> Recipiente
      {
        id: 'e-cond-rec',
        source: 'cond-1',
        sourceHandle: 'liquid_out',
        target: 'rec-1',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'condensing_liquid',
          customLabel: 'Líquido Condensado',
          diameterInch: '5/8"',
          pressureBar: 10.2,
          temperatureC: 40.0,
        },
      },
      // Líquido: Recipiente -> Filtro
      {
        id: 'e-rec-flt',
        source: 'rec-1',
        sourceHandle: 'outlet',
        target: 'filter-1',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'subcooled_liquid',
          diameterInch: '1/2"',
          pressureBar: 10.0,
          temperatureC: 35.0,
        },
      },
      // Líquido: Filtro -> Visor
      {
        id: 'e-flt-sgt',
        source: 'filter-1',
        sourceHandle: 'outlet',
        target: 'sight-1',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'subcooled_liquid',
          diameterInch: '1/2"',
        },
      },
      // Líquido Subenfriado: Visor -> TXV
      {
        id: 'e-sgt-txv',
        source: 'sight-1',
        sourceHandle: 'outlet',
        target: 'txv-1',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'subcooled_liquid',
          customLabel: 'Línea de Líquido',
          diameterInch: '1/2"',
        },
      },
      // Expansión: TXV -> Evaporador
      {
        id: 'e-txv-evap',
        source: 'txv-1',
        sourceHandle: 'outlet',
        target: 'evap-1',
        targetHandle: 'liquid_in',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'two_phase_flashing',
          customLabel: 'Mezcla Bifásica Fría',
          diameterInch: '1/2"',
          pressureBar: 2.0,
          temperatureC: -10.0,
        },
      },
      // Evaporación: Evaporador -> Acumulador
      {
        id: 'e-evap-acc',
        source: 'evap-1',
        sourceHandle: 'gas_out',
        target: 'acc-1',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'evaporating_vapor',
          customLabel: 'Gas Frío de Cámara',
          diameterInch: '1-1/8"',
        },
      },
      // Succión: Acumulador -> Compresor
      {
        id: 'e-acc-cmp',
        source: 'acc-1',
        sourceHandle: 'outlet',
        target: 'comp-1',
        targetHandle: 'suction',
        type: 'refrigerantPipe',
        data: {
          pipeState: 'suction_superheated',
          customLabel: 'Línea de Aspiración Seca',
          diameterInch: '1-1/8"',
          pressureBar: 2.0,
          temperatureC: -5.0,
        },
      },
    ],
  },
  {
    id: 'preset_economizer_evi',
    name: 'Ciclo con Economizador e Inyección de Vapor (EVI)',
    description: 'Esquema de alto rendimiento con subenfriamiento por botella flash e inyección de vapor a media presión.',
    category: 'Avanzado',
    refrigerant: 'R410A',
    iconName: 'Zap',
    nodes: [
      {
        id: 'cmp-evi',
        type: 'schematicNode',
        position: { x: 380, y: 340 },
        data: {
          componentType: 'compressor_scroll',
          label: 'Compresor con EVI',
          tag: 'CMP-EVI',
          modelNumber: 'Copeland ZFI',
          powerKw: 11.0,
          pressureOutBar: 26.0,
          pressureInBar: 5.2,
          isEnergized: true,
        },
      },
      {
        id: 'cond-evi',
        type: 'schematicNode',
        position: { x: 620, y: 120 },
        data: {
          componentType: 'condenser_air',
          label: 'Condensador HP',
          tag: 'COND-01',
          capacityKw: 35.0,
          setpointTempC: 45.0,
        },
      },
      {
        id: 'flash-tank',
        type: 'schematicNode',
        position: { x: 620, y: 320 },
        data: {
          componentType: 'flash_tank_economizer',
          label: 'Botella Flash Economizadora',
          tag: 'FLSH-01',
          volumeL: 18.0,
          pressureOutBar: 12.5,
          tempOutC: 15.0,
        },
      },
      {
        id: 'txv-main',
        type: 'schematicNode',
        position: { x: 620, y: 520 },
        data: {
          componentType: 'expansion_valve_eev',
          label: 'Válvula EEV Principal',
          tag: 'EEV-01',
          superheatK: 4.5,
        },
      },
      {
        id: 'evap-evi',
        type: 'schematicNode',
        position: { x: 380, y: 520 },
        data: {
          componentType: 'evaporator_dx_air',
          label: 'Evaporador',
          tag: 'EVAP-01',
          capacityKw: 22.0,
          setpointTempC: 0.0,
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'cmp-evi',
        sourceHandle: 'discharge',
        target: 'cond-evi',
        targetHandle: 'gas_in',
        type: 'refrigerantPipe',
        data: { pipeState: 'discharge_superheated', customLabel: 'Descarga HP (26 bar)' },
      },
      {
        id: 'e2',
        source: 'cond-evi',
        sourceHandle: 'liquid_out',
        target: 'flash-tank',
        targetHandle: 'liquid_in',
        type: 'refrigerantPipe',
        data: { pipeState: 'condensing_liquid' },
      },
      {
        id: 'e3',
        source: 'flash-tank',
        sourceHandle: 'flash_gas',
        target: 'cmp-evi',
        targetHandle: 'evi',
        type: 'refrigerantPipe',
        data: { pipeState: 'intermediate_pressure', customLabel: 'Inyección Flash EVI (12.5 bar)', pressureBar: 12.5, temperatureC: 15.0 },
      },
      {
        id: 'e4',
        source: 'flash-tank',
        sourceHandle: 'liquid_out',
        target: 'txv-main',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: { pipeState: 'subcooled_liquid', customLabel: 'Líquido Altamente Subenfriado' },
      },
      {
        id: 'e5',
        source: 'txv-main',
        sourceHandle: 'outlet',
        target: 'evap-evi',
        targetHandle: 'liquid_in',
        type: 'refrigerantPipe',
        data: { pipeState: 'two_phase_flashing' },
      },
      {
        id: 'e6',
        source: 'evap-evi',
        sourceHandle: 'gas_out',
        target: 'cmp-evi',
        targetHandle: 'suction',
        type: 'refrigerantPipe',
        data: { pipeState: 'suction_superheated', customLabel: 'Aspiración LP (5.2 bar)' },
      },
    ],
  },
  {
    id: 'preset_co2_transcritical_booster',
    name: 'Central CO₂ Booster Transcrítico (R744)',
    description: 'Sistema transcrítico para refrigeración comercial con Gas Cooler, Válvula HPV, Flash Tank y compresores MT y LT.',
    category: 'Transcrítico CO₂',
    refrigerant: 'R744',
    iconName: 'Flame',
    nodes: [
      {
        id: 'cmp-mt',
        type: 'schematicNode',
        position: { x: 360, y: 260 },
        data: {
          componentType: 'compressor_reciprocating',
          label: 'Compresor Media Temp (MT)',
          tag: 'CMP-MT',
          modelNumber: 'Dorin CD400',
          powerKw: 18.5,
          pressureOutBar: 90.0,
          pressureInBar: 28.0,
          isEnergized: true,
        },
      },
      {
        id: 'gas-cooler',
        type: 'schematicNode',
        position: { x: 580, y: 100 },
        data: {
          componentType: 'gas_cooler_co2',
          label: 'Gas Cooler Transcrítico',
          tag: 'GC-01',
          capacityKw: 65.0,
          tempOutC: 32.0,
        },
      },
      {
        id: 'hpv-valve',
        type: 'schematicNode',
        position: { x: 780, y: 180 },
        data: {
          componentType: 'expansion_valve_eev',
          label: 'Válvula Alta Presión (HPV)',
          tag: 'HPV-01',
          setpointBar: 90.0,
          openingPercent: 45,
        },
      },
      {
        id: 'flash-tank-co2',
        type: 'schematicNode',
        position: { x: 780, y: 320 },
        data: {
          componentType: 'co2_flash_tank',
          label: 'Depósito Flash CO₂',
          tag: 'REC-CO2',
          modelNumber: 'Bitzer CO₂ Flash Vessel (PS 52 bar)',
          volumeL: 50.0,
          pressureOutBar: 35.0,
          tempOutC: 0.0,
        },
      },
      {
        id: 'evap-mt',
        type: 'schematicNode',
        position: { x: 580, y: 440 },
        data: {
          componentType: 'evaporator_dx_air',
          label: 'Evaporadores MT (+2°C)',
          tag: 'EVAP-MT',
          capacityKw: 30.0,
          setpointTempC: -4.0,
        },
      },
      {
        id: 'cmp-lt',
        type: 'schematicNode',
        position: { x: 200, y: 480 },
        data: {
          componentType: 'compressor_reciprocating',
          label: 'Compresor Baja Temp (LT Booster)',
          tag: 'CMP-LT',
          modelNumber: 'Dorin CD200',
          powerKw: 7.5,
          pressureOutBar: 28.0,
          pressureInBar: 14.0,
          isEnergized: true,
        },
      },
      {
        id: 'evap-lt',
        type: 'schematicNode',
        position: { x: 380, y: 600 },
        data: {
          componentType: 'evaporator_dx_air',
          label: 'Evaporadores LT (-25°C)',
          tag: 'EVAP-LT',
          capacityKw: 12.0,
          setpointTempC: -30.0,
        },
      },
    ],
    edges: [
      {
        id: 'e-gc-in',
        source: 'cmp-mt',
        sourceHandle: 'discharge',
        target: 'gas-cooler',
        targetHandle: 'gas_in',
        type: 'refrigerantPipe',
        data: { pipeState: 'discharge_superheated', customLabel: 'Gas Supercrítico (90 bar)', pressureBar: 90.0, temperatureC: 85.0 },
      },
      {
        id: 'e-hpv-in',
        source: 'gas-cooler',
        sourceHandle: 'gas_out',
        target: 'hpv-valve',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: { pipeState: 'condensing_liquid', pressureBar: 90.0, temperatureC: 32.0 },
      },
      {
        id: 'e-flash-in',
        source: 'hpv-valve',
        sourceHandle: 'outlet',
        target: 'flash-tank-co2',
        targetHandle: 'biphasic_in',
        type: 'refrigerantPipe',
        data: { pipeState: 'two_phase_flashing', pressureBar: 35.0, temperatureC: 0.0 },
      },
      {
        id: 'e-flash-gas',
        source: 'flash-tank-co2',
        sourceHandle: 'flash_gas',
        target: 'cmp-mt',
        targetHandle: 'suction',
        type: 'refrigerantPipe',
        data: { pipeState: 'intermediate_pressure', customLabel: 'Flash Gas Bypass (35 bar)' },
      },
      {
        id: 'e-mt-feed',
        source: 'flash-tank-co2',
        sourceHandle: 'liquid_out',
        target: 'evap-mt',
        targetHandle: 'liquid_in',
        type: 'refrigerantPipe',
        data: { pipeState: 'subcooled_liquid' },
      },
      {
        id: 'e-mt-suction',
        source: 'evap-mt',
        sourceHandle: 'gas_out',
        target: 'cmp-mt',
        targetHandle: 'suction',
        type: 'refrigerantPipe',
        data: { pipeState: 'suction_superheated', customLabel: 'Aspiración MT (28 bar)' },
      },
      {
        id: 'e-lt-evap',
        source: 'evap-lt',
        sourceHandle: 'gas_out',
        target: 'cmp-lt',
        targetHandle: 'suction',
        type: 'refrigerantPipe',
        data: { pipeState: 'suction_superheated', customLabel: 'Aspiración LT (14 bar)' },
      },
      {
        id: 'e-lt-discharge',
        source: 'cmp-lt',
        sourceHandle: 'discharge',
        target: 'cmp-mt',
        targetHandle: 'suction',
        type: 'refrigerantPipe',
        data: { pipeState: 'discharge_superheated', customLabel: 'Descarga Booster a Succión MT' },
      },
    ],
  },
  {
    id: 'preset_heat_pump_reversible',
    name: 'Bomba de Calor Reversible (4 Vías)',
    description: 'Sistema reversible con válvula inversora de 4 vías para calefacción y climatización.',
    category: 'Bombas de Calor',
    refrigerant: 'R32',
    iconName: 'Repeat',
    nodes: [
      {
        id: 'comp-hp',
        type: 'schematicNode',
        position: { x: 450, y: 350 },
        data: {
          componentType: 'compressor_inverter',
          label: 'Compresor Inverter R32',
          tag: 'CMP-INV',
          modelNumber: 'Mitsubishi Twin-Rotary',
          powerKw: 4.2,
          cop: 4.8,
          isEnergized: true,
        },
      },
      {
        id: 'valve-4way',
        type: 'schematicNode',
        position: { x: 450, y: 200 },
        data: {
          componentType: 'four_way_reversing_valve',
          label: 'Válvula Inversora 4 Vías',
          tag: '4WY-01',
          modelNumber: 'Sanhua SHF-4',
        },
      },
      {
        id: 'outdoor-coil',
        type: 'schematicNode',
        position: { x: 200, y: 200 },
        data: {
          componentType: 'condenser_air',
          label: 'Batería Exterior',
          tag: 'COIL-OUT',
          capacityKw: 12.0,
        },
      },
      {
        id: 'indoor-coil',
        type: 'schematicNode',
        position: { x: 700, y: 200 },
        data: {
          componentType: 'evaporator_dx_air',
          label: 'Batería Interior',
          tag: 'COIL-IN',
          capacityKw: 10.5,
        },
      },
      {
        id: 'eev-bidir',
        type: 'schematicNode',
        position: { x: 450, y: 480 },
        data: {
          componentType: 'expansion_valve_eev',
          label: 'Válvula EEV Bidireccional',
          tag: 'EEV-BI',
          openingPercent: 55,
        },
      },
      {
        id: 'acc-hp',
        type: 'schematicNode',
        position: { x: 300, y: 350 },
        data: {
          componentType: 'suction_accumulator',
          label: 'Acumulador de Aspiración',
          tag: 'ACC-01',
          volumeL: 6.0,
        },
      },
    ],
    edges: [
      {
        id: 'e-comp-4way',
        source: 'comp-hp',
        sourceHandle: 'discharge',
        target: 'valve-4way',
        targetHandle: 'discharge_in',
        type: 'refrigerantPipe',
        data: { pipeState: 'discharge_superheated' },
      },
      {
        id: 'e-4way-outdoor',
        source: 'valve-4way',
        sourceHandle: 'outdoor_coil',
        target: 'outdoor-coil',
        targetHandle: 'gas_in',
        type: 'refrigerantPipe',
        data: { pipeState: 'discharge_superheated' },
      },
      {
        id: 'e-outdoor-eev',
        source: 'outdoor-coil',
        sourceHandle: 'liquid_out',
        target: 'eev-bidir',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: { pipeState: 'subcooled_liquid' },
      },
      {
        id: 'e-eev-indoor',
        source: 'eev-bidir',
        sourceHandle: 'outlet',
        target: 'indoor-coil',
        targetHandle: 'liquid_in',
        type: 'refrigerantPipe',
        data: { pipeState: 'two_phase_flashing' },
      },
      {
        id: 'e-indoor-4way',
        source: 'indoor-coil',
        sourceHandle: 'gas_out',
        target: 'valve-4way',
        targetHandle: 'indoor_coil',
        type: 'refrigerantPipe',
        data: { pipeState: 'evaporating_vapor' },
      },
      {
        id: 'e-4way-acc',
        source: 'valve-4way',
        sourceHandle: 'suction_out',
        target: 'acc-hp',
        targetHandle: 'inlet',
        type: 'refrigerantPipe',
        data: { pipeState: 'suction_superheated' },
      },
      {
        id: 'e-acc-comp',
        source: 'acc-hp',
        sourceHandle: 'outlet',
        target: 'comp-hp',
        targetHandle: 'suction',
        type: 'refrigerantPipe',
        data: { pipeState: 'suction_superheated' },
      },
    ],
  },
];
