import { SchematicComponentCategory, SchematicComponentDefinition, SchematicComponentType } from '../../../types/schematic';

export const COMPONENT_DEFINITIONS: Record<SchematicComponentType, SchematicComponentDefinition> = {
  // --- COMPRESORES & BOMBAS ---
  compressor_scroll: {
    type: 'compressor_scroll',
    category: 'compressors',
    name: 'Compresor Scroll',
    description: 'Compresor hermético de espiral orbital para aire acondicionado y media temperatura.',
    defaultLabel: 'Compresor Scroll',
    defaultTagPrefix: 'CMP-SCR',
    defaultModel: 'Copeland ZB45KCE',
    dimensions: { width: 120, height: 125 },
    defaultSpecs: {
      powerKw: 7.5,
      displacementM3h: 17.2,
      pressureInBar: 2.1,
      pressureOutBar: 14.5,
      tempInC: -5.0,
      tempOutC: 68.0,
      fluidName: 'R134a',
    },
    ports: [
      { id: 'suction', name: 'Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'left', hint: 'Vapor frío a baja presión proveniente del evaporador / acumulador' },
      { id: 'discharge', name: 'Descarga (HP)', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Gas muy caliente a alta presión hacia el condensador' },
      { id: 'evi', name: 'Inyección EVI / Vapor', shortCode: 'EVI', kind: 'intermediate', position: 'top', hint: 'Puerto para inyección de vapor de economizador a presión intermedia' },
      { id: 'oil_sight', name: 'Cárter de Aceite', shortCode: 'OIL', kind: 'oil', position: 'bottom', hint: 'Conexión para visor, igualación o retorno de aceite al cárter' },
    ],
  },
  compressor_reciprocating: {
    type: 'compressor_reciprocating',
    category: 'compressors',
    name: 'Compresor Alternativo (Pistón)',
    description: 'Compresor semi-hermético de pistones para refrigeración comercial e industrial.',
    defaultLabel: 'Compresor Pistón',
    defaultTagPrefix: 'CMP-REC',
    defaultModel: 'Bitzer 4CES-9Y',
    dimensions: { width: 120, height: 125 },
    defaultSpecs: {
      powerKw: 9.2,
      displacementM3h: 32.5,
      pressureInBar: 1.8,
      pressureOutBar: 15.2,
      tempInC: -8.0,
      tempOutC: 75.0,
    },
    ports: [
      { id: 'suction', name: 'Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'left', hint: 'Vapor frío a baja presión (Entrada a culata de baja)' },
      { id: 'discharge', name: 'Descarga (HP)', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Gas caliente comprimido a alta presión hacia condensador' },
      { id: 'oil_equalization', name: 'Retorno Aceite', shortCode: 'OIL', kind: 'oil', position: 'bottom', hint: 'Línea de compensación y retorno de aceite al cárter' },
    ],
  },
  compressor_screw: {
    type: 'compressor_screw',
    category: 'compressors',
    name: 'Compresor de Tornillo',
    description: 'Compresor de doble rotor helicoidal para grandes enfriadoras y cámaras frigoríficas.',
    defaultLabel: 'Compresor Tornillo',
    defaultTagPrefix: 'CMP-SCW',
    defaultModel: 'Bitzer CSH8573',
    dimensions: { width: 130, height: 120 },
    defaultSpecs: {
      powerKw: 45.0,
      displacementM3h: 180.0,
      capacityKw: 130.0,
      pressureInBar: 2.5,
      pressureOutBar: 16.0,
    },
    ports: [
      { id: 'suction', name: 'Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'left', hint: 'Aspiración de gran caudal de vapor frío' },
      { id: 'discharge', name: 'Descarga (HP)', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Descarga hacia separador de aceite y condensador' },
      { id: 'eco', name: 'Puerto Eco', shortCode: 'ECO', kind: 'intermediate', position: 'top', hint: 'Entrada de economizador para aumento de potencia frigorífica' },
      { id: 'oil_in', name: 'Inyección Aceite', shortCode: 'OIL', kind: 'oil', position: 'bottom', hint: 'Inyección de aceite enfriado para estanqueidad y lubricación' },
    ],
  },
  compressor_inverter: {
    type: 'compressor_inverter',
    category: 'compressors',
    name: 'Compresor Inverter (VFD)',
    description: 'Compresor de velocidad variable modulado por variador de frecuencia (20-90 Hz).',
    defaultLabel: 'Compresor Inverter',
    defaultTagPrefix: 'CMP-INV',
    defaultModel: 'Daikin Variable BLDC',
    dimensions: { width: 120, height: 125 },
    defaultSpecs: {
      powerKw: 5.5,
      frequencyHz: 60,
      cop: 4.2,
      pressureInBar: 2.2,
      pressureOutBar: 14.0,
    },
    ports: [
      { id: 'suction', name: 'Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'left', hint: 'Aspiración modulada en función de la demanda' },
      { id: 'discharge', name: 'Descarga (HP)', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Descarga con control variable de caudal' },
    ],
  },
  compressor_compound: {
    type: 'compressor_compound',
    category: 'compressors',
    name: 'Compresor Compound (2 Etapas)',
    description: 'Compresor de doble etapa en un solo bloque para congelación extrema (-40°C).',
    defaultLabel: 'Compresor Compound',
    defaultTagPrefix: 'CMP-2STG',
    dimensions: { width: 135, height: 125 },
    defaultSpecs: {
      powerKw: 15.0,
      pressureInBar: 0.8,
      pressureOutBar: 15.0,
      capacityKw: 22.0,
    },
    ports: [
      { id: 'lp_suction', name: 'Aspiración Baja', shortCode: 'ASP-BT', kind: 'suction', position: 'left', hint: 'Aspiración de baja presión desde evaporador de congelación' },
      { id: 'inter_discharge', name: 'Intermedia (MP)', shortCode: 'INT', kind: 'intermediate', position: 'top', hint: 'Descarga intermedia hacia enfriador intercooler / subenfriador' },
      { id: 'hp_discharge', name: 'Descarga Alta', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Descarga final a alta presión hacia el condensador' },
    ],
  },
  refrigerant_pump: {
    type: 'refrigerant_pump',
    category: 'compressors',
    name: 'Bomba de Refrigerante Líquido',
    description: 'Bomba centrífuga hermética para recirculación de amoníaco R717 o CO₂ en sistemas inundados.',
    defaultLabel: 'Bomba Refrigerante',
    defaultTagPrefix: 'PUMP-01',
    dimensions: { width: 110, height: 110 },
    defaultSpecs: {
      powerKw: 1.5,
      displacementM3h: 8.5,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'ENT', kind: 'subcooled', position: 'left', hint: 'Alimentación de refrigerante líquido desde el separador de gotas' },
      { id: 'outlet', name: 'Impulsión Líquido', shortCode: 'SAL', kind: 'subcooled', position: 'right', hint: 'Impulsión forzada a los evaporadores inundados' },
    ],
  },

  // --- INTERCAMBIADORES DE CALOR ---
  condenser_air: {
    type: 'condenser_air',
    category: 'heat_exchangers',
    name: 'Condensador por Aire',
    description: 'Batería aleteada con ventiladores axiales para condensación por aire exterior.',
    defaultLabel: 'Condensador de Aire',
    defaultTagPrefix: 'COND-01',
    defaultModel: 'Guentner / Frimetal',
    dimensions: { width: 130, height: 120 },
    defaultSpecs: {
      capacityKw: 28.5,
      setpointTempC: 45.0,
      subcoolingK: 4.0,
    },
    ports: [
      { id: 'gas_in', name: 'Entrada Gas (HP)', shortCode: 'GAS-IN', kind: 'discharge', position: 'left', hint: 'Entrada de vapor caliente desde la descarga del compresor' },
      { id: 'liquid_out', name: 'Salida Líquido (HP)', shortCode: 'LIQ-OUT', kind: 'condensed', position: 'right', hint: 'Salida de refrigerante líquido condensado hacia recipiente' },
    ],
  },
  condenser_water_plate: {
    type: 'condenser_water_plate',
    category: 'heat_exchangers',
    name: 'Condensador de Placas (Agua)',
    description: 'Intercambiador de placas soldadas para condensación por agua de pozo o torre.',
    defaultLabel: 'Condensador Placas',
    defaultTagPrefix: 'COND-PLT',
    dimensions: { width: 125, height: 125 },
    defaultSpecs: {
      capacityKw: 35.0,
      setpointTempC: 38.0,
      subcoolingK: 5.0,
    },
    ports: [
      { id: 'ref_in', name: 'Gas Refrigerante', shortCode: 'GAS-IN', kind: 'discharge', position: 'top', hint: 'Entrada vapor caliente de refrigerante' },
      { id: 'ref_out', name: 'Líquido Refrigerante', shortCode: 'LIQ-OUT', kind: 'condensed', position: 'bottom', hint: 'Salida líquido condensado hacia recipiente' },
      { id: 'water_in', name: 'Agua Entrada', shortCode: 'H2O-IN', kind: 'water_in', position: 'left', hint: 'Entrada de agua fría de refrigeración (ej. 25°C)' },
      { id: 'water_out', name: 'Agua Salida', shortCode: 'H2O-OUT', kind: 'water_out', position: 'right', hint: 'Salida de agua caliente hacia torre o geotermia (ej. 32°C)' },
    ],
  },
  condenser_evaporative: {
    type: 'condenser_evaporative',
    category: 'heat_exchangers',
    name: 'Condensador Evaporativo',
    description: 'Torre de condensación con lluvia de agua pulverizada y tiro forzado de aire.',
    defaultLabel: 'Condensador Evap.',
    defaultTagPrefix: 'COND-EVP',
    dimensions: { width: 130, height: 130 },
    defaultSpecs: {
      capacityKw: 80.0,
      setpointTempC: 32.0,
    },
    ports: [
      { id: 'gas_in', name: 'Entrada Gas (HP)', shortCode: 'GAS-IN', kind: 'discharge', position: 'left', hint: 'Entrada de vapor caliente desde la descarga' },
      { id: 'liquid_out', name: 'Salida Líquido (HP)', shortCode: 'LIQ-OUT', kind: 'condensed', position: 'right', hint: 'Salida de líquido condensado hacia el recipiente' },
    ],
  },
  gas_cooler_co2: {
    type: 'gas_cooler_co2',
    category: 'heat_exchangers',
    name: 'Gas Cooler Transcrítico CO₂',
    description: 'Intercambiador de muy alta presión (120 bar) para enfriar el gas supercrítico de CO₂ (R744).',
    defaultLabel: 'Gas Cooler CO₂',
    defaultTagPrefix: 'GC-CO2',
    dimensions: { width: 130, height: 120 },
    defaultSpecs: {
      capacityKw: 45.0,
      pressureOutBar: 90.0,
      tempOutC: 32.0,
    },
    ports: [
      { id: 'gas_in', name: 'Gas Supercrítico (HP)', shortCode: 'GAS-IN', kind: 'discharge', position: 'left', hint: 'Entrada de gas de CO₂ supercrítico a 90-110 bar y 85-120°C' },
      { id: 'gas_out', name: 'Gas Enfriado Out', shortCode: 'GAS-OUT', kind: 'condensed', position: 'right', hint: 'Salida de gas enfriado hacia la válvula de alta presión (HPV)' },
    ],
  },
  evaporator_dx_air: {
    type: 'evaporator_dx_air',
    category: 'heat_exchangers',
    name: 'Evaporador DX por Aire',
    description: 'Evaporador de expansión directa aleteado con ventiladores para cámaras frigoríficas.',
    defaultLabel: 'Evaporador DX',
    defaultTagPrefix: 'EVAP-01',
    defaultModel: 'Alfa Laval / Lu-Ve',
    dimensions: { width: 130, height: 120 },
    defaultSpecs: {
      capacityKw: 18.0,
      setpointTempC: -5.0,
      superheatK: 6.0,
    },
    ports: [
      { id: 'liquid_in', name: 'Entrada Bifásica (LP)', shortCode: 'EXP-IN', kind: 'expansion_out', position: 'left', hint: 'Entrada de mezcla bifásica fría desde la válvula de expansión' },
      { id: 'gas_out', name: 'Salida Vapor (LP)', shortCode: 'VAP-OUT', kind: 'evaporated', position: 'right', hint: 'Salida de vapor recalentado hacia la aspiración del compresor' },
    ],
  },
  evaporator_plate_chiller: {
    type: 'evaporator_plate_chiller',
    category: 'heat_exchangers',
    name: 'Evaporador de Placas (Enfriadora)',
    description: 'Evaporador de placas soldadas para enfriamiento de agua o salmuera a 7°C.',
    defaultLabel: 'Evaporador Placas',
    defaultTagPrefix: 'EVAP-PLT',
    dimensions: { width: 125, height: 125 },
    defaultSpecs: {
      capacityKw: 30.0,
      setpointTempC: 3.0,
      superheatK: 5.0,
    },
    ports: [
      { id: 'ref_in', name: 'Entrada Refrigerante', shortCode: 'REF-IN', kind: 'expansion_out', position: 'bottom', hint: 'Entrada de refrigerante desde válvula de expansión' },
      { id: 'ref_out', name: 'Salida Vapor Seco', shortCode: 'REF-OUT', kind: 'evaporated', position: 'top', hint: 'Salida de vapor frío hacia la aspiración' },
      { id: 'water_in', name: 'Entrada Agua Retorno', shortCode: 'H2O-IN', kind: 'water_in', position: 'left', hint: 'Entrada de agua retornada del edificio (ej. 12°C)' },
      { id: 'water_out', name: 'Salida Agua Fría', shortCode: 'H2O-OUT', kind: 'water_out', position: 'right', hint: 'Salida de agua enfriada hacia fan-coils (ej. 7°C)' },
    ],
  },
  evaporator_flooded: {
    type: 'evaporator_flooded',
    category: 'heat_exchangers',
    name: 'Evaporador Inundado',
    description: 'Evaporador de carcasa inundado donde los tubos están completamente sumergidos en refrigerante.',
    defaultLabel: 'Evaporador Inundado',
    defaultTagPrefix: 'EVAP-FLD',
    dimensions: { width: 135, height: 125 },
    defaultSpecs: {
      capacityKw: 100.0,
      setpointTempC: -15.0,
    },
    ports: [
      { id: 'liquid_in', name: 'Alimentación Líquido', shortCode: 'LIQ-IN', kind: 'expansion_out', position: 'bottom', hint: 'Entrada de refrigerante líquido desde la bomba o flotador' },
      { id: 'gas_out', name: 'Aspiración Seca', shortCode: 'ASP-OUT', kind: 'evaporated', position: 'top', hint: 'Salida de vapor libre de gotas hacia el compresor' },
    ],
  },
  heat_exchanger_slhx: {
    type: 'heat_exchanger_slhx',
    category: 'heat_exchangers',
    name: 'Intercambiador Líquido-Aspiración (IHX)',
    description: 'Subenfría el líquido de alta presión con el vapor frío de aspiración para ganar eficiencia.',
    defaultLabel: 'IHX Líquido-Gas',
    defaultTagPrefix: 'HX-IHX',
    dimensions: { width: 125, height: 115 },
    defaultSpecs: {
      subcoolingK: 8.0,
      superheatK: 10.0,
    },
    ports: [
      { id: 'liq_in', name: 'Líquido Entrada (HP)', shortCode: 'LIQ-IN', kind: 'condensed', position: 'top', hint: 'Entrada de líquido caliente desde el condensador / recipiente' },
      { id: 'liq_out', name: 'Líquido Subenfriado', shortCode: 'LIQ-OUT', kind: 'subcooled', position: 'bottom', hint: 'Salida de líquido altamente subenfriado hacia la TXV' },
      { id: 'gas_in', name: 'Vapor Frío Entrada', shortCode: 'GAS-IN', kind: 'evaporated', position: 'left', hint: 'Entrada de vapor frío procedente del evaporador' },
      { id: 'gas_out', name: 'Vapor Recalentado Out', shortCode: 'GAS-OUT', kind: 'suction', position: 'right', hint: 'Salida de vapor sobrecalentado seco al compresor' },
    ],
  },
  desuperheater: {
    type: 'desuperheater',
    category: 'heat_exchangers',
    name: 'Desrecalentador / Recuperador Calor',
    description: 'Aprovecha el calor residual sensible de la descarga para precalentar ACS.',
    defaultLabel: 'Desrecalentador',
    defaultTagPrefix: 'HX-REC',
    dimensions: { width: 120, height: 110 },
    defaultSpecs: {
      capacityKw: 12.0,
    },
    ports: [
      { id: 'gas_in', name: 'Entrada Descarga HP', shortCode: 'GAS-IN', kind: 'discharge', position: 'left', hint: 'Entrada directa del gas caliente de compresión' },
      { id: 'gas_out', name: 'Salida Gas al Cond', shortCode: 'GAS-OUT', kind: 'discharge', position: 'right', hint: 'Salida de gas desrecalentado hacia el condensador principal' },
      { id: 'water_in', name: 'Agua Fría ACS', shortCode: 'ACS-IN', kind: 'water_in', position: 'bottom', hint: 'Entrada de agua de red (ej. 15°C)' },
      { id: 'water_out', name: 'Agua Caliente ACS', shortCode: 'ACS-OUT', kind: 'water_out', position: 'top', hint: 'Salida de agua precalentada (ej. 55°C)' },
    ],
  },

  // --- EXPANSION & REGULACION ---
  expansion_valve_txv: {
    type: 'expansion_valve_txv',
    category: 'expansion',
    name: 'Válvula Expansión Termostática (TXV)',
    description: 'Válvula termostática con bulbo sensor y toma de compensación externa de presión.',
    defaultLabel: 'Válvula TXV',
    defaultTagPrefix: 'TXV-01',
    defaultModel: 'Danfoss TE2 / T2',
    dimensions: { width: 110, height: 110 },
    defaultSpecs: {
      superheatK: 5.0,
      capacityKw: 14.5,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido HP', shortCode: 'LIQ-IN', kind: 'subcooled', position: 'left', hint: 'Entrada de líquido subenfriado a alta presión' },
      { id: 'outlet', name: 'Salida Bifásica LP', shortCode: 'EXP-OUT', kind: 'expansion_out', position: 'right', hint: 'Salida de refrigerante atomizado a baja presión hacia evaporador' },
      { id: 'equalization', name: 'Compensación Externa', shortCode: 'IGU', kind: 'equalization', position: 'bottom', hint: 'Tubo fino conectado a la salida del evaporador para compensar caída de presión' },
      { id: 'bulb', name: 'Bulbo Termostático', shortCode: 'BULB', kind: 'bulb', position: 'top', hint: 'Bulbo fijado al tubo de aspiración para censar el recalentamiento' },
    ],
  },
  expansion_valve_eev: {
    type: 'expansion_valve_eev',
    category: 'expansion',
    name: 'Válvula Expansión Electrónica (EEV)',
    description: 'Válvula paso a paso motorizada para control milimétrico de recalentamiento.',
    defaultLabel: 'Válvula EEV',
    defaultTagPrefix: 'EEV-01',
    defaultModel: 'Carel E2V / Danfoss ETS',
    dimensions: { width: 110, height: 110 },
    defaultSpecs: {
      openingPercent: 65,
      superheatK: 4.0,
      capacityKw: 25.0,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'LIQ-IN', kind: 'subcooled', position: 'left', hint: 'Entrada de líquido a alta presión' },
      { id: 'outlet', name: 'Salida Expansión', shortCode: 'EXP-OUT', kind: 'expansion_out', position: 'right', hint: 'Salida dosificada a baja presión hacia el evaporador' },
    ],
  },
  capillary_tube: {
    type: 'capillary_tube',
    category: 'expansion',
    name: 'Tubo Capilar',
    description: 'Tubo de cobre de pequeño diámetro para expansión por pérdida de carga fija.',
    defaultLabel: 'Tubo Capilar',
    defaultTagPrefix: 'CAP-01',
    dimensions: { width: 100, height: 75 },
    defaultSpecs: {
      capacityKw: 1.2,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'ENT', kind: 'subcooled', position: 'left', hint: 'Entrada desde el filtro deshidratador' },
      { id: 'outlet', name: 'Salida Evaporador', shortCode: 'SAL', kind: 'expansion_out', position: 'right', hint: 'Salida hacia el inicio del evaporador' },
    ],
  },
  float_valve: {
    type: 'float_valve',
    category: 'expansion',
    name: 'Válvula de Flotador',
    description: 'Regula el nivel de refrigerante líquido en sistemas inundados.',
    defaultLabel: 'Válvula Flotador',
    defaultTagPrefix: 'FLT-01',
    dimensions: { width: 105, height: 105 },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'IN', kind: 'subcooled', position: 'left', hint: 'Entrada de líquido' },
      { id: 'outlet', name: 'Salida Regulada', shortCode: 'OUT', kind: 'expansion_out', position: 'right', hint: 'Salida controlada por nivel de boya' },
    ],
  },
  regulator_epr_kvp: {
    type: 'regulator_epr_kvp',
    category: 'expansion',
    name: 'Regulador Presión Evaporación (KVP)',
    description: 'Impide que la presión del evaporador caiga por debajo de un valor prefijado.',
    defaultLabel: 'Regulador KVP',
    defaultTagPrefix: 'REG-KVP',
    dimensions: { width: 105, height: 105 },
    defaultSpecs: {
      setpointBar: 3.2,
    },
    ports: [
      { id: 'inlet', name: 'Entrada desde Evap', shortCode: 'EVAP', kind: 'evaporated', position: 'left', hint: 'Conexión a la salida del evaporador' },
      { id: 'outlet', name: 'Salida al Compresor', shortCode: 'COMP', kind: 'suction', position: 'right', hint: 'Conexión hacia la línea de aspiración general' },
    ],
  },
  regulator_cpr_kvl: {
    type: 'regulator_cpr_kvl',
    category: 'expansion',
    name: 'Regulador Presión Cárter (KVL)',
    description: 'Protege el motor del compresor limitando la presión máxima de succión en el arranque.',
    defaultLabel: 'Regulador KVL',
    defaultTagPrefix: 'REG-KVL',
    dimensions: { width: 105, height: 105 },
    defaultSpecs: {
      setpointBar: 4.5,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Línea Succión', shortCode: 'SUC-IN', kind: 'evaporated', position: 'left', hint: 'Entrada desde los evaporadores' },
      { id: 'outlet', name: 'Salida al Cárter', shortCode: 'CMP-IN', kind: 'suction', position: 'right', hint: 'Salida regulada directa a la aspiración del compresor' },
    ],
  },
  regulator_kvr: {
    type: 'regulator_kvr',
    category: 'expansion',
    name: 'Regulador Condensación (KVR)',
    description: 'Mantiene una presión de condensación mínima suficiente durante el invierno.',
    defaultLabel: 'Regulador KVR',
    defaultTagPrefix: 'REG-KVR',
    dimensions: { width: 105, height: 105 },
    defaultSpecs: {
      setpointBar: 12.0,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Condensador', shortCode: 'COND', kind: 'condensed', position: 'left', hint: 'Entrada desde la salida del condensador' },
      { id: 'outlet', name: 'Salida al Recipiente', shortCode: 'REC', kind: 'subcooled', position: 'right', hint: 'Salida hacia el depósito de líquido' },
    ],
  },

  // --- RECIPIENTES & ACEITE ---
  liquid_receiver_vertical: {
    type: 'liquid_receiver_vertical',
    category: 'vessels',
    name: 'Recipiente de Líquido Vertical',
    description: 'Depósito vertical para almacenar la reserva de líquido refrigerante condensado.',
    defaultLabel: 'Recipiente Líquido',
    defaultTagPrefix: 'REC-01',
    dimensions: { width: 110, height: 135 },
    defaultSpecs: {
      volumeL: 25.0,
      pressureOutBar: 14.5,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Condensado', shortCode: 'COND-IN', kind: 'condensed', position: 'top', hint: 'Entrada superior de líquido procedente del condensador' },
      { id: 'outlet', name: 'Salida Líquido a TXV', shortCode: 'LIQ-OUT', kind: 'subcooled', position: 'bottom', hint: 'Salida inferior de columna continua de líquido hacia filtro y TXV' },
    ],
  },
  liquid_receiver_horizontal: {
    type: 'liquid_receiver_horizontal',
    category: 'vessels',
    name: 'Recipiente Líquido Horizontal',
    description: 'Depósito horizontal de alta capacidad para centrales frigoríficas industriales.',
    defaultLabel: 'Recipiente Horiz.',
    defaultTagPrefix: 'REC-HOR',
    dimensions: { width: 140, height: 105 },
    defaultSpecs: {
      volumeL: 120.0,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Condensado', shortCode: 'IN', kind: 'condensed', position: 'top', hint: 'Entrada superior desde condensador' },
      { id: 'outlet', name: 'Salida Líquido', shortCode: 'OUT', kind: 'subcooled', position: 'bottom', hint: 'Salida hacia línea de líquido de la central' },
    ],
  },
  suction_accumulator: {
    type: 'suction_accumulator',
    category: 'vessels',
    name: 'Acumulador de Succión',
    description: 'Impide que gotas de refrigerante líquido no evaporado alcancen los cilindros del compresor.',
    defaultLabel: 'Acumulador Succión',
    defaultTagPrefix: 'ACC-01',
    dimensions: { width: 110, height: 135 },
    defaultSpecs: {
      volumeL: 12.0,
    },
    ports: [
      { id: 'inlet', name: 'Entrada desde Evap', shortCode: 'EVAP-IN', kind: 'evaporated', position: 'top', hint: 'Entrada de gas húmedo procedente de la línea de evaporación' },
      { id: 'outlet', name: 'Salida a Compresor', shortCode: 'CMP-OUT', kind: 'suction', position: 'right', hint: 'Salida superior de vapor 100% seco hacia el compresor' },
    ],
  },
  oil_separator: {
    type: 'oil_separator',
    category: 'vessels',
    name: 'Separador de Aceite',
    description: 'Separa el lubricante arrastrado en la descarga y lo retorna de forma continua al cárter.',
    defaultLabel: 'Separador Aceite',
    defaultTagPrefix: 'SEP-OIL',
    dimensions: { width: 110, height: 130 },
    ports: [
      { id: 'gas_in', name: 'Entrada Descarga HP', shortCode: 'DESC-IN', kind: 'discharge', position: 'left', hint: 'Entrada de mezcla gas caliente + microgotas de aceite' },
      { id: 'gas_out', name: 'Gas al Condensador', shortCode: 'GAS-OUT', kind: 'discharge', position: 'right', hint: 'Gas limpio de aceite hacia el condensador' },
      { id: 'oil_return', name: 'Retorno Aceite Cárter', shortCode: 'OIL-RET', kind: 'oil', position: 'bottom', hint: 'Tubo de retorno de aceite regulado por flotador interno al cárter' },
    ],
  },
  oil_reservoir: {
    type: 'oil_reservoir',
    category: 'vessels',
    name: 'Depósito Colector Aceite',
    description: 'Almacén centralizado de aceite para alimentación regulada a múltiples compresores.',
    defaultLabel: 'Depósito Aceite',
    defaultTagPrefix: 'RES-OIL',
    dimensions: { width: 110, height: 125 },
    ports: [
      { id: 'oil_in', name: 'Entrada Separadores', shortCode: 'OIL-IN', kind: 'oil', position: 'top', hint: 'Entrada de aceite recogido de los separadores' },
      { id: 'oil_out', name: 'Salida a Reguladores', shortCode: 'OIL-OUT', kind: 'oil', position: 'bottom', hint: 'Salida a reguladores de nivel electrónicos de cada compresor' },
    ],
  },
  flash_tank_economizer: {
    type: 'flash_tank_economizer',
    category: 'vessels',
    name: 'Botella Flash Economizador',
    description: 'Vaso de expansión intermedia que genera vapor flash para inyección EVI y subenfría el líquido.',
    defaultLabel: 'Botella Flash',
    defaultTagPrefix: 'FLSH-01',
    dimensions: { width: 120, height: 135 },
    defaultSpecs: {
      pressureOutBar: 6.5,
      tempOutC: 12.0,
      volumeL: 15.0,
    },
    ports: [
      { id: 'liquid_in', name: 'Entrada Expansión 1', shortCode: 'EXP-1', kind: 'expansion_out', position: 'top', hint: 'Entrada de líquido tras primera caída de presión' },
      { id: 'flash_gas', name: 'Vapor Flash a Compresor', shortCode: 'EVI-GAS', kind: 'intermediate', position: 'right', hint: 'Vapor saturado intermedio hacia el puerto EVI del compresor' },
      { id: 'liquid_out', name: 'Líquido Subenfriado a TXV', shortCode: 'LIQ-SUB', kind: 'subcooled', position: 'bottom', hint: 'Líquido frío subenfriado hacia la válvula de evaporación' },
    ],
  },
  co2_flash_tank: {
    type: 'co2_flash_tank',
    category: 'vessels',
    name: 'Depósito Flash CO₂ (Separador Líquido / Gas)',
    description: 'Recipiente de media presión (35-45 bar) para sistemas CO₂ transcríticos/subcríticos. Separa por gravedad la mezcla bifásica en vapor flash superior y líquido saturado inferior puro.',
    defaultLabel: 'Depósito Flash CO₂',
    defaultTagPrefix: 'REC-CO2',
    defaultModel: 'Bitzer / Danfoss CO₂ Flash Vessel (PS 52 bar)',
    dimensions: { width: 125, height: 145 },
    defaultSpecs: {
      volumeL: 50.0,
      pressureOutBar: 38.0,
      tempOutC: 3.5,
      fluidName: 'R744 (CO₂)',
    },
    ports: [
      { id: 'biphasic_in', name: 'Entrada Mezcla HPV (Bifásica)', shortCode: 'HPV-IN', kind: 'expansion_out', position: 'left', hint: 'Entrada lateral de mezcla bifásica proveniente de la válvula de alta presión HPV' },
      { id: 'flash_gas', name: 'Salida Flash Gas (Vapor MP)', shortCode: 'GAS-MP', kind: 'intermediate', position: 'top', hint: 'Salida superior de vapor saturado hacia la válvula FGV o compresor en paralelo' },
      { id: 'liquid_out', name: 'Salida Líquido Saturado MP', shortCode: 'LIQ-MP', kind: 'subcooled', position: 'bottom', hint: 'Salida inferior de columna continua de líquido puro hacia evaporadores MT/LT' },
      { id: 'safety_aux', name: 'Válvula de Seguridad / Purga', shortCode: 'SEG', kind: 'discharge', position: 'right', hint: 'Toma para doble válvula de seguridad de media presión (52 bar), ecualización o retorno' },
    ],
  },
  filter_drier: {
    type: 'filter_drier',
    category: 'accessories',
    name: 'Filtro Deshidratador',
    description: 'Filtro de tamiz molecular para atrapar partículas sólidas y absorber trazas de agua ácida.',
    defaultLabel: 'Filtro Deshidratador',
    defaultTagPrefix: 'FLT-01',
    defaultModel: 'Danfoss DML 163',
    dimensions: { width: 105, height: 75 },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'ENT', kind: 'subcooled', position: 'left', hint: 'Entrada desde el recipiente de líquido' },
      { id: 'outlet', name: 'Salida Líquido', shortCode: 'SAL', kind: 'subcooled', position: 'right', hint: 'Salida limpia y seca hacia el visor y la TXV' },
    ],
  },
  sight_glass: {
    type: 'sight_glass',
    category: 'accessories',
    name: 'Visor Líquido / Humedad',
    description: 'Mirilla transparente con corona de sales indicadoras de humedad (Verde = Seco, Amarillo = Húmedo).',
    defaultLabel: 'Visor Líquido',
    defaultTagPrefix: 'SGT-01',
    dimensions: { width: 95, height: 75 },
    ports: [
      { id: 'inlet', name: 'Entrada', shortCode: 'ENT', kind: 'subcooled', position: 'left', hint: 'Entrada de línea de líquido' },
      { id: 'outlet', name: 'Salida', shortCode: 'SAL', kind: 'subcooled', position: 'right', hint: 'Salida hacia válvula de expansión' },
    ],
  },

  // --- VALVULAS & SEGURIDAD ---
  four_way_reversing_valve: {
    type: 'four_way_reversing_valve',
    category: 'valves',
    name: 'Válvula Inversora 4 Vías',
    description: 'Permite invertir el ciclo en bombas de calor para alternar entre modo Frío y modo Calor.',
    defaultLabel: 'Válvula 4 Vías',
    defaultTagPrefix: '4WY-01',
    dimensions: { width: 125, height: 125 },
    ports: [
      { id: 'discharge_in', name: 'Descarga Compresor', shortCode: 'DESC', kind: 'discharge', position: 'top', hint: 'Conexión a la descarga de gas caliente del compresor' },
      { id: 'suction_out', name: 'Aspiración Compresor', shortCode: 'ASP', kind: 'suction', position: 'bottom', hint: 'Conexión a la aspiración permanente del compresor' },
      { id: 'outdoor_coil', name: 'Batería Exterior', shortCode: 'EXT', kind: 'generic', position: 'left', hint: 'Conexión a la batería exterior (Condensador en verano / Evaporador en invierno)' },
      { id: 'indoor_coil', name: 'Batería Interior', shortCode: 'INT', kind: 'generic', position: 'right', hint: 'Conexión a la batería interior (Evaporador en verano / Condensador en invierno)' },
    ],
  },
  solenoid_valve: {
    type: 'solenoid_valve',
    category: 'valves',
    name: 'Válvula Solenoide (NC)',
    description: 'Válvula electromagnética on/off para corte de líquido en parada o bombeo de vaciado (pump down).',
    defaultLabel: 'Válvula Solenoide',
    defaultTagPrefix: 'SOL-01',
    dimensions: { width: 105, height: 100 },
    defaultSpecs: {
      voltageV: 230,
    },
    ports: [
      { id: 'inlet', name: 'Entrada', shortCode: 'IN', kind: 'generic', position: 'left', hint: 'Entrada de refrigerante' },
      { id: 'outlet', name: 'Salida', shortCode: 'OUT', kind: 'generic', position: 'right', hint: 'Salida habilitada al energizar la bobina eléctrica' },
    ],
  },
  check_valve: {
    type: 'check_valve',
    category: 'valves',
    name: 'Válvula Retención (Check)',
    description: 'Permite el paso en un único sentido impidiendo retornos indebidos de refrigerante.',
    defaultLabel: 'Válvula Check',
    defaultTagPrefix: 'CHK-01',
    dimensions: { width: 100, height: 75 },
    ports: [
      { id: 'inlet', name: 'Entrada Flujo', shortCode: 'IN', kind: 'generic', position: 'left', hint: 'Sentido permitido del refrigerante' },
      { id: 'outlet', name: 'Salida Flujo', shortCode: 'OUT', kind: 'generic', position: 'right', hint: 'Salida (bloquea el retorno en sentido contrario)' },
    ],
  },
  safety_relief_valve: {
    type: 'safety_relief_valve',
    category: 'valves',
    name: 'Válvula Seguridad Alivio',
    description: 'Válvula mecánica tarada para descargar presión a la atmósfera en caso de incendio o sobrepresión.',
    defaultLabel: 'Válvula Seguridad',
    defaultTagPrefix: 'PRV-01',
    dimensions: { width: 95, height: 100 },
    defaultSpecs: {
      setpointBar: 28.0,
    },
    ports: [
      { id: 'inlet', name: 'Toma Recipiente', shortCode: 'REC', kind: 'generic', position: 'bottom', hint: 'Conexión a la parte superior del recipiente de líquido' },
      { id: 'vent', name: 'Escape Seguridad', shortCode: 'VENT', kind: 'generic', position: 'top', hint: 'Tubo de venteo hacia el exterior del edificio' },
    ],
  },
  hot_gas_bypass_valve: {
    type: 'hot_gas_bypass_valve',
    category: 'valves',
    name: 'Válvula Bypass Gas Caliente',
    description: 'Inyecta gas de descarga caliente en la baja presión para modular capacidad y evitar congelación.',
    defaultLabel: 'Bypass Gas Caliente',
    defaultTagPrefix: 'HGBP-01',
    dimensions: { width: 110, height: 110 },
    defaultSpecs: {
      setpointBar: 2.0,
    },
    ports: [
      { id: 'hp_in', name: 'Entrada Descarga HP', shortCode: 'HP-IN', kind: 'discharge', position: 'left', hint: 'Toma de gas caliente directo desde la descarga' },
      { id: 'lp_out', name: 'Salida Inyección LP', shortCode: 'LP-OUT', kind: 'hot_gas_bypass', position: 'right', hint: 'Inyección a la entrada del evaporador o a la aspiración' },
      { id: 'equalization', name: 'Toma Presión', shortCode: 'IGU', kind: 'equalization', position: 'bottom', hint: 'Línea de presión de referencia' },
    ],
  },
  ball_service_valve: {
    type: 'ball_service_valve',
    category: 'valves',
    name: 'Válvula de Bola / Servicio',
    description: 'Válvula de aislamiento manual de 1/4 de vuelta para mantenimiento y corte de tramos.',
    defaultLabel: 'Válvula Bola',
    defaultTagPrefix: 'VLV-01',
    dimensions: { width: 95, height: 85 },
    ports: [
      { id: 'inlet', name: 'Entrada', shortCode: 'IN', kind: 'generic', position: 'left', hint: 'Entrada de tubería' },
      { id: 'outlet', name: 'Salida', shortCode: 'OUT', kind: 'generic', position: 'right', hint: 'Salida de tubería' },
    ],
  },

  // --- INSTRUMENTACION & SENSORES ---
  gauge_pressure_hp: {
    type: 'gauge_pressure_hp',
    category: 'instruments',
    name: 'Manómetro Alta Presión (HP)',
    description: 'Manómetro dial rojo para lectura de presión de descarga y condensación.',
    defaultLabel: 'Manómetro HP',
    defaultTagPrefix: 'PI-HP',
    dimensions: { width: 95, height: 100 },
    defaultSpecs: {
      measuredValue: 14.8,
      measuredUnit: 'bar',
    },
    ports: [
      { id: 'inlet', name: 'Toma Presión', shortCode: 'HP', kind: 'discharge', position: 'bottom', hint: 'Toma de manómetro en línea de descarga o condensador' },
    ],
  },
  gauge_pressure_lp: {
    type: 'gauge_pressure_lp',
    category: 'instruments',
    name: 'Manómetro Baja Presión (LP)',
    description: 'Manómetro dial azul para lectura de presión de aspiración y evaporación.',
    defaultLabel: 'Manómetro LP',
    defaultTagPrefix: 'PI-LP',
    dimensions: { width: 95, height: 100 },
    defaultSpecs: {
      measuredValue: 2.1,
      measuredUnit: 'bar',
    },
    ports: [
      { id: 'inlet', name: 'Toma Presión', shortCode: 'LP', kind: 'suction', position: 'bottom', hint: 'Toma de manómetro en línea de aspiración o evaporador' },
    ],
  },
  sensor_temperature: {
    type: 'sensor_temperature',
    category: 'instruments',
    name: 'Sonda Temperatura (NTC/PT100)',
    description: 'Sensor térmico de contacto para medición de temperaturas en tuberías.',
    defaultLabel: 'Sonda Temp.',
    defaultTagPrefix: 'TI-01',
    dimensions: { width: 90, height: 90 },
    defaultSpecs: {
      measuredValue: -5.5,
      measuredUnit: '°C',
    },
    ports: [
      { id: 'inlet', name: 'Sonda Contacto', shortCode: 'T', kind: 'generic', position: 'bottom', hint: 'Fijación por abrazadera al tubo para medir temperatura superficial' },
    ],
  },
  pressure_switch: {
    type: 'pressure_switch',
    category: 'instruments',
    name: 'Presostato Dual Alta / Baja',
    description: 'Dispositivo de seguridad que corta la maniobra eléctrica ante sobrepresión o falta de gas.',
    defaultLabel: 'Presostato Dual',
    defaultTagPrefix: 'PS-01',
    dimensions: { width: 110, height: 105 },
    defaultSpecs: {
      setpointBar: 18.0,
    },
    ports: [
      { id: 'hp_tap', name: 'Toma Alta (HP)', shortCode: 'HP', kind: 'discharge', position: 'right', hint: 'Capilar conectado a la descarga' },
      { id: 'lp_tap', name: 'Toma Baja (LP)', shortCode: 'LP', kind: 'suction', position: 'left', hint: 'Capilar conectado a la aspiración' },
    ],
  },
  flow_meter: {
    type: 'flow_meter',
    category: 'instruments',
    name: 'Caudalímetro Másico',
    description: 'Medidor en línea de caudal másico [kg/s] o volumétrico [m³/h] de refrigerante.',
    defaultLabel: 'Caudalímetro',
    defaultTagPrefix: 'FI-01',
    dimensions: { width: 105, height: 85 },
    defaultSpecs: {
      measuredValue: 0.045,
      measuredUnit: 'kg/s',
    },
    ports: [
      { id: 'inlet', name: 'Entrada', shortCode: 'IN', kind: 'generic', position: 'left', hint: 'Entrada de flujo' },
      { id: 'outlet', name: 'Salida', shortCode: 'OUT', kind: 'generic', position: 'right', hint: 'Salida de flujo' },
    ],
  },
  power_meter: {
    type: 'power_meter',
    category: 'instruments',
    name: 'Vatímetro / Analizador Red',
    description: 'Medidor de potencia eléctrica activa [kW], consumo energético [kWh] y factor de potencia.',
    defaultLabel: 'Vatímetro',
    defaultTagPrefix: 'EI-01',
    dimensions: { width: 100, height: 100 },
    defaultSpecs: {
      measuredValue: 8.2,
      measuredUnit: 'kW',
    },
    ports: [
      { id: 'comp_link', name: 'Alimentación Motor', shortCode: 'PWR', kind: 'generic', position: 'bottom', hint: 'Conexión a cuadro de maniobra del compresor' },
    ],
  },

  // --- UNIONES & DERIVACIONES DE TUBERÍA ---
  pipe_union_straight: {
    type: 'pipe_union_straight',
    category: 'fittings',
    name: 'Unión Bilateral Recta',
    description: 'Racor pasante / manguito de unión para empalmar dos tramos de tubería en línea recta.',
    defaultLabel: 'Unión Recta',
    defaultTagPrefix: 'UN-01',
    dimensions: { width: 85, height: 75 },
    defaultSpecs: {},
    ports: [
      { id: 'port_1', name: 'Extremo 1 (Izq)', shortCode: '1', kind: 'generic', position: 'left', hint: 'Conexión para tubería de entrada' },
      { id: 'port_2', name: 'Extremo 2 (Der)', shortCode: '2', kind: 'generic', position: 'right', hint: 'Conexión para tubería de salida' },
    ],
  },
  pipe_union_elbow: {
    type: 'pipe_union_elbow',
    category: 'fittings',
    name: 'Codo a 90° (Curva)',
    description: 'Codo de tubería a 90 grados para cambio de dirección de flujo. Rotable a cualquier cuadrante.',
    defaultLabel: 'Codo 90°',
    defaultTagPrefix: 'CD-01',
    dimensions: { width: 85, height: 85 },
    defaultSpecs: {},
    ports: [
      { id: 'port_1', name: 'Extremo Lateral (Izq)', shortCode: '1', kind: 'generic', position: 'left', hint: 'Entrada lateral (rota 90° para cambiar posición)' },
      { id: 'port_2', name: 'Extremo Inferior (Abajo)', shortCode: '2', kind: 'generic', position: 'bottom', hint: 'Salida a 90 grados (rota para orientar arriba, derecha, etc.)' },
    ],
  },
  pipe_union_tee: {
    type: 'pipe_union_tee',
    category: 'fittings',
    name: 'Unión en T (Derivación 3 Vías)',
    description: 'Te de tubería para ramificación, bifurcación o mezcla de refrigerante en 3 vías.',
    defaultLabel: 'Te Derivación',
    defaultTagPrefix: 'TE-01',
    dimensions: { width: 90, height: 90 },
    defaultSpecs: {},
    ports: [
      { id: 'main_left', name: 'Paso Principal (Izq)', shortCode: '1', kind: 'generic', position: 'left', hint: 'Línea de paso principal izquierda' },
      { id: 'main_right', name: 'Paso Principal (Der)', shortCode: '2', kind: 'generic', position: 'right', hint: 'Línea de paso principal derecha' },
      { id: 'branch', name: 'Ramal Derivación (T)', shortCode: '3', kind: 'generic', position: 'bottom', hint: 'Bifurcación perpendicular (rota para orientar el ramal arriba o hacia un lado)' },
    ],
  },
  pipe_union_cross: {
    type: 'pipe_union_cross',
    category: 'fittings',
    name: 'Cruz 4 Vías / Manifold',
    description: 'Distribuidor cuádruple en cruz para interconexión simétrica de hasta 4 conexiones.',
    defaultLabel: 'Cruz 4 Vías',
    defaultTagPrefix: 'CR-01',
    dimensions: { width: 95, height: 95 },
    defaultSpecs: {},
    ports: [
      { id: 'port_left', name: 'Vía Izquierda', shortCode: 'O', kind: 'generic', position: 'left', hint: 'Vía horizontal izquierda' },
      { id: 'port_right', name: 'Vía Derecha', shortCode: 'E', kind: 'generic', position: 'right', hint: 'Vía horizontal derecha' },
      { id: 'port_top', name: 'Vía Superior', shortCode: 'N', kind: 'generic', position: 'top', hint: 'Vía vertical superior' },
      { id: 'port_bottom', name: 'Vía Inferior', shortCode: 'S', kind: 'generic', position: 'bottom', hint: 'Vía vertical inferior' },
    ],
  },
  pipe_junction_dot: {
    type: 'pipe_junction_dot',
    category: 'fittings',
    name: 'Punto de Empalme Compacto',
    description: 'Nodo de conexión rápida multi-vía de tamaño compacto para interconectar tuberías densas.',
    defaultLabel: 'Empalme',
    defaultTagPrefix: 'ND-01',
    dimensions: { width: 70, height: 70 },
    defaultSpecs: {},
    ports: [
      { id: 'port_left', name: 'Vía Izquierda', shortCode: '←', kind: 'generic', position: 'left', hint: 'Conexión Oeste' },
      { id: 'port_right', name: 'Vía Derecha', shortCode: '→', kind: 'generic', position: 'right', hint: 'Conexión Este' },
      { id: 'port_top', name: 'Vía Superior', shortCode: '↑', kind: 'generic', position: 'top', hint: 'Conexión Norte' },
      { id: 'port_bottom', name: 'Vía Inferior', shortCode: '↓', kind: 'generic', position: 'bottom', hint: 'Conexión Sur' },
    ],
  },

  // --- CÁMARAS FRIGORÍFICAS & RECINTOS ---
  cold_room_conservation: {
    type: 'cold_room_conservation',
    category: 'chambers',
    name: 'Cámara de Conservación (+0°C a +4°C)',
    description: 'Recinto isotermo para productos refrigerados frescos con panel PUR 80mm y puerta pivotante.',
    defaultLabel: 'Cámara Conservación',
    defaultTagPrefix: 'CAM-01',
    dimensions: { width: 140, height: 130 },
    defaultSpecs: {
      setpointTempC: 2.0,
      chamberVolumeM3: 45.0,
      chamberUValue: 0.28,
      productMassKg: 1200.0,
    },
    ports: [
      { id: 'inlet_exp', name: 'Alimentación Inyección (TXV)', shortCode: 'EXP', kind: 'expansion_out', position: 'left', hint: 'Entrada de mezcla bifásica hacia el evaporador interno' },
      { id: 'outlet_suc', name: 'Retorno Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'right', hint: 'Línea de aspiración de gas evaporado hacia compresores' },
      { id: 'door_access', name: 'Acceso / Puerta Frigorífica', shortCode: 'PTR', kind: 'generic', position: 'bottom', hint: 'Control de apertura/cierre de puerta para infiltraciones' },
      { id: 'control_sensor', name: 'Sonda Temperatura / Maniobra', shortCode: 'SND', kind: 'generic', position: 'top', hint: 'Conexión de termostato y maniobra de solenoide' },
    ],
  },
  cold_room_freezer: {
    type: 'cold_room_freezer',
    category: 'chambers',
    name: 'Cámara de Congelados (-18°C a -25°C)',
    description: 'Recinto para almacenamiento de ultracongelados con panel PUR 120mm, resistencia en marco y suelo calefactado.',
    defaultLabel: 'Cámara Congelados',
    defaultTagPrefix: 'CAM-BT',
    dimensions: { width: 140, height: 130 },
    defaultSpecs: {
      setpointTempC: -20.0,
      chamberVolumeM3: 60.0,
      chamberUValue: 0.18,
      productMassKg: 2500.0,
    },
    ports: [
      { id: 'inlet_exp', name: 'Alimentación Inyección (TXV)', shortCode: 'EXP', kind: 'expansion_out', position: 'left', hint: 'Línea de líquido expansionado a baja temperatura' },
      { id: 'outlet_suc', name: 'Retorno Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'right', hint: 'Vapor muy frío hacia batería de compresores' },
      { id: 'door_access', name: 'Puerta Calefactada', shortCode: 'PTR', kind: 'generic', position: 'bottom', hint: 'Apertura de puerta de baja temperatura' },
      { id: 'control_sensor', name: 'Sonda Térmica BT', shortCode: 'SND', kind: 'generic', position: 'top', hint: 'Sonda para termostato y desescarches periódicos' },
    ],
  },
  cold_room_blast_chiller: {
    type: 'cold_room_blast_chiller',
    category: 'chambers',
    name: 'Túnel de Abatimiento Rápido (-35°C)',
    description: 'Recinto de abatimiento criogénico / acelerado con ventilación de alta velocidad para reducir temperatura central.',
    defaultLabel: 'Túnel Abatimiento',
    defaultTagPrefix: 'TUN-01',
    dimensions: { width: 140, height: 130 },
    defaultSpecs: {
      setpointTempC: -35.0,
      chamberVolumeM3: 20.0,
      chamberUValue: 0.16,
      productMassKg: 800.0,
    },
    ports: [
      { id: 'inlet_exp', name: 'Inyección Alta Potencia', shortCode: 'EXP', kind: 'expansion_out', position: 'left', hint: 'Alimentación de evaporador de alto rendimiento' },
      { id: 'outlet_suc', name: 'Aspiración Caudal Elevado', shortCode: 'ASP', kind: 'suction', position: 'right', hint: 'Retorno masivo de vapor a baja presión' },
      { id: 'door_access', name: 'Puerta Enclavamiento', shortCode: 'PTR', kind: 'generic', position: 'bottom', hint: 'Acceso de carros de producto' },
      { id: 'control_sensor', name: 'Sonda Pincho de Producto', shortCode: 'SND', kind: 'generic', position: 'top', hint: 'Sonda central de corazón de producto' },
    ],
  },
  conditioned_room: {
    type: 'conditioned_room',
    category: 'chambers',
    name: 'Sala Climatizada / Despiece (+12°C a +16°C)',
    description: 'Recinto para manipulación y envasado de alimentos con personal laboral y renovación higiénica de aire.',
    defaultLabel: 'Sala Climatizada',
    defaultTagPrefix: 'SALA-01',
    dimensions: { width: 140, height: 130 },
    defaultSpecs: {
      setpointTempC: 14.0,
      chamberVolumeM3: 120.0,
      chamberUValue: 0.35,
      productMassKg: 600.0,
    },
    ports: [
      { id: 'inlet_exp', name: 'Línea Fría Climatización', shortCode: 'EXP', kind: 'expansion_out', position: 'left', hint: 'Entrada refrigerante a fancoil o evaporador de techo' },
      { id: 'outlet_suc', name: 'Retorno Gas Aspiración', shortCode: 'ASP', kind: 'suction', position: 'right', hint: 'Retorno gas hacia central frigorífica' },
      { id: 'door_access', name: 'Acceso Esclusa / Puerta', shortCode: 'PTR', kind: 'generic', position: 'bottom', hint: 'Paso de personal y carretillas' },
      { id: 'control_sensor', name: 'Sensor Confort / Higrometría', shortCode: 'SND', kind: 'generic', position: 'top', hint: 'Sensor combinado de temperatura y humedad' },
    ],
  },

  cold_room_fermentation: {
    type: 'cold_room_fermentation',
    category: 'chambers',
    name: 'Cámara de Fermentación Controlada',
    description: 'Cámara con ciclo de frío para bloqueo y ciclo de calor/humedad para fermentación de panadería/pastelería.',
    defaultLabel: 'Cámara Fermentación',
    defaultTagPrefix: 'FERM-01',
    dimensions: { width: 140, height: 130 },
    defaultSpecs: {
      setpointTempC: 4.0,
      chamberVolumeM3: 25.0,
      chamberUValue: 0.25,
      productMassKg: 500.0,
    },
    ports: [
      { id: 'inlet_exp', name: 'Alimentación Evaporador', shortCode: 'EXP', kind: 'expansion_out', position: 'left', hint: 'Línea de líquido frío para ciclo de retardo/bloqueo' },
      { id: 'outlet_suc', name: 'Aspiración', shortCode: 'ASP', kind: 'suction', position: 'right', hint: 'Retorno de refrigerante al compresor' },
      { id: 'door_access', name: 'Puerta Cámara', shortCode: 'PTR', kind: 'generic', position: 'bottom', hint: 'Puerta con junta estanca y ventana térmica' },
      { id: 'control_sensor', name: 'Sonda Higrometría y Temp', shortCode: 'SND', kind: 'generic', position: 'top', hint: 'Sonda de control psicrométrico' },
    ],
  },
  cold_room_ripening: {
    type: 'cold_room_ripening',
    category: 'chambers',
    name: 'Cámara de Maduración de Frutas',
    description: 'Recinto con control preciso de temperatura, inyección de etileno y ventilación para plátanos, aguacates y fruta.',
    defaultLabel: 'Cámara Maduración',
    defaultTagPrefix: 'MAD-01',
    dimensions: { width: 140, height: 130 },
    defaultSpecs: {
      setpointTempC: 16.0,
      chamberVolumeM3: 90.0,
      chamberUValue: 0.26,
      productMassKg: 4000.0,
    },
    ports: [
      { id: 'inlet_exp', name: 'Entrada Frío Maduración', shortCode: 'EXP', kind: 'expansion_out', position: 'left', hint: 'Refrigeración para absorber el calor de respiración' },
      { id: 'outlet_suc', name: 'Aspiración Gas', shortCode: 'ASP', kind: 'suction', position: 'right', hint: 'Retorno a central frigorífica' },
      { id: 'door_access', name: 'Puerta Guillotina', shortCode: 'PTR', kind: 'generic', position: 'bottom', hint: 'Acceso para carretillas elevadoras de palets' },
      { id: 'control_sensor', name: 'Analizador CO2/Etileno', shortCode: 'SND', kind: 'generic', position: 'top', hint: 'Monitor de concentración de gases y temperatura' },
    ],
  },
  cold_room_drying: {
    type: 'cold_room_drying',
    category: 'chambers',
    name: 'Secadero / Curado de Embutidos y Jamones',
    description: 'Secadero con batería de frío y batería de poscalentamiento por gas caliente para deshumidificación continua.',
    defaultLabel: 'Secadero Curado',
    defaultTagPrefix: 'SEC-01',
    dimensions: { width: 140, height: 130 },
    defaultSpecs: {
      setpointTempC: 12.0,
      chamberVolumeM3: 150.0,
      chamberUValue: 0.28,
      productMassKg: 6000.0,
    },
    ports: [
      { id: 'inlet_exp', name: 'Batería Deshumidificadora', shortCode: 'EXP', kind: 'expansion_out', position: 'left', hint: 'Enfriamiento y condensación de humedad' },
      { id: 'outlet_suc', name: 'Aspiración Evaporador', shortCode: 'ASP', kind: 'suction', position: 'right', hint: 'Retorno de gas refrigerante' },
      { id: 'door_access', name: 'Acceso Secadero', shortCode: 'PTR', kind: 'generic', position: 'bottom', hint: 'Puerta hermética de secado' },
      { id: 'control_sensor', name: 'Psicrómetro Seco/Húmedo', shortCode: 'SND', kind: 'generic', position: 'top', hint: 'Control de entalpía y humedad relativa %' },
    ],
  },
  ice_storage_room: {
    type: 'ice_storage_room',
    category: 'chambers',
    name: 'Silo / Depósito de Hielo en Escamas (-5°C)',
    description: 'Cámara depósito para conservación de hielo con serpentín en techo para evitar que el hielo se apelmace.',
    defaultLabel: 'Silo de Hielo',
    defaultTagPrefix: 'SILO-01',
    dimensions: { width: 140, height: 130 },
    defaultSpecs: {
      setpointTempC: -5.0,
      chamberVolumeM3: 50.0,
      chamberUValue: 0.20,
      productMassKg: 10000.0,
    },
    ports: [
      { id: 'inlet_exp', name: 'Entrada Serpentín Techo', shortCode: 'EXP', kind: 'expansion_out', position: 'left', hint: 'Refrigerante a baja temperatura para techo frío' },
      { id: 'outlet_suc', name: 'Aspiración Serpentín', shortCode: 'ASP', kind: 'suction', position: 'right', hint: 'Retorno gas' },
      { id: 'door_access', name: 'Trampilla Descarga Hielo', shortCode: 'PTR', kind: 'generic', position: 'bottom', hint: 'Boca de salida del sinfín de hielo' },
      { id: 'control_sensor', name: 'Sonda Nivel y Temp', shortCode: 'SND', kind: 'generic', position: 'top', hint: 'Control de temperatura interior del silo' },
    ],
  },

  // --- INSTALACIÓN ELÉCTRICA: CUADROS, ACOMETIDA Y PROTECCIONES ---
  electrical_panel_main: {
    type: 'electrical_panel_main',
    category: 'electrical',
    name: 'Cuadro General de Mando y Protección (CGFP)',
    description: 'Armario de distribución trifásico 400V con Interruptor General de Corte, barras de distribución y mandos.',
    defaultLabel: 'Cuadro Eléctrico',
    defaultTagPrefix: 'CGP-01',
    dimensions: { width: 135, height: 130 },
    defaultSpecs: {
      voltageV: 400,
      maxContractedPowerKw: 45.0,
      demandLimitKw: 35.0,
    },
    ports: [
      { id: 'mains_in', name: 'Acometida Red (L1-L2-L3-N)', shortCode: 'RED', kind: 'electric_power', position: 'top', hint: 'Entrada de red eléctrica exterior de suministro' },
      { id: 'feed_comp', name: 'Línea de Fuerza Compresores', shortCode: 'L-CMP', kind: 'electric_power', position: 'right', hint: 'Alimentación protegida para compresores principales' },
      { id: 'feed_aux', name: 'Línea Evaporadores y Ventiladores', shortCode: 'L-AUX', kind: 'electric_power', position: 'bottom', hint: 'Alimentación para ventiladores de condensador y evaporadores' },
      { id: 'ctrl_bus', name: 'Circuito de Maniobra (230V)', shortCode: 'MAN', kind: 'electric_control', position: 'left', hint: 'Control de termostatos, presostatos y seguridades' },
    ],
  },
  power_supply_terminal: {
    type: 'power_supply_terminal',
    category: 'electrical',
    name: 'Bornera de Acometida Red (L1-L2-L3-N-PE)',
    description: 'Bornes de paso y distribución de acometida eléctrica para conexión de cables de red y repartidor.',
    defaultLabel: 'Bornera Red',
    defaultTagPrefix: 'X1',
    dimensions: { width: 110, height: 85 },
    defaultSpecs: { voltageV: 400 },
    ports: [
      { id: 'term_l1', name: 'Fase L1 (R)', shortCode: 'L1', kind: 'electric_power', position: 'top', hint: 'Llegada fase 1' },
      { id: 'term_l2', name: 'Fase L2 (S)', shortCode: 'L2', kind: 'electric_power', position: 'left', hint: 'Llegada fase 2' },
      { id: 'term_l3', name: 'Fase L3 (T)', shortCode: 'L3', kind: 'electric_power', position: 'right', hint: 'Llegada fase 3' },
      { id: 'term_n', name: 'Neutro (N)', shortCode: 'N', kind: 'electric_neutral', position: 'bottom', hint: 'Neutro de red de alimentación' },
    ],
  },
  ground_earth: {
    type: 'ground_earth',
    category: 'electrical',
    name: 'Borne de Puesta a Tierra (PE ⏚)',
    description: 'Punto de conexión equipotencial de seguridad a la red de tierra (conductor verde/amarillo).',
    defaultLabel: 'Tierra PE',
    defaultTagPrefix: 'PE',
    dimensions: { width: 75, height: 75 },
    defaultSpecs: {},
    ports: [
      { id: 'pe_in', name: 'Entrada Tierra PE', shortCode: 'PE1', kind: 'electric_ground', position: 'top', hint: 'Conexión a pica de tierra o chasis' },
      { id: 'pe_out', name: 'Derivación PE', shortCode: 'PE2', kind: 'electric_ground', position: 'bottom', hint: 'Protección al motor o equipo' },
    ],
  },
  circuit_breaker_mcb: {
    type: 'circuit_breaker_mcb',
    category: 'electrical',
    name: 'Interruptor Magnetotérmico (Disyuntor MCB)',
    description: 'Protección contra sobrecargas térmicas bimetálicas (I²t) y cortocircuitos con rearme manual.',
    defaultLabel: 'Magnetotérmico',
    defaultTagPrefix: 'Q1',
    dimensions: { width: 95, height: 105 },
    defaultSpecs: {
      ratedCurrentA: 16.0,
      curveType: 'C',
    },
    ports: [
      { id: 'line_in', name: 'Línea Entrada (1 / 3 / 5)', shortCode: 'IN', kind: 'electric_power', position: 'top', hint: 'Llegada de fase desde red o barra distribuidora' },
      { id: 'load_out', name: 'Salida Protegida (2 / 4 / 6)', shortCode: 'OUT', kind: 'electric_power', position: 'bottom', hint: 'Salida hacia contactor o carga' },
    ],
  },
  residual_current_device: {
    type: 'residual_current_device',
    category: 'electrical',
    name: 'Interruptor Diferencial (ID / RCD 30mA)',
    description: 'Aparato de protección contra derivaciones y contactos directos/indirectos por fuga a tierra.',
    defaultLabel: 'Diferencial ID',
    defaultTagPrefix: 'F1',
    dimensions: { width: 100, height: 110 },
    defaultSpecs: { ratedCurrentA: 40.0, voltageV: 400 },
    ports: [
      { id: 'line_in', name: 'Entrada Red Diferencial', shortCode: 'IN', kind: 'electric_power', position: 'top', hint: 'Llegada aguas arriba' },
      { id: 'load_out', name: 'Salida Diferencial', shortCode: 'OUT', kind: 'electric_power', position: 'bottom', hint: 'Salida aguas abajo hacia magnetotérmicos' },
    ],
  },
  motor_protection_switch: {
    type: 'motor_protection_switch',
    category: 'electrical',
    name: 'Disyuntor Guardamotor Magnetotérmico',
    description: 'Interruptor de protección de motor con regulación de intensidad térmica Ir y corte magnético rápido.',
    defaultLabel: 'Guardamotor',
    defaultTagPrefix: 'QM1',
    dimensions: { width: 100, height: 110 },
    defaultSpecs: { ratedCurrentA: 10.0, overloadCurrentSettingA: 8.5 },
    ports: [
      { id: 'line_in', name: 'L1-L2-L3 Entrada', shortCode: '1-3-5', kind: 'electric_power', position: 'top', hint: 'Entrada de red de fuerza' },
      { id: 'load_out', name: 'T1-T2-T3 Salida', shortCode: '2-4-6', kind: 'electric_power', position: 'bottom', hint: 'Salida hacia contactor de motor' },
      { id: 'aux_no', name: 'Contacto Señalización Disparo', shortCode: '13-14', kind: 'electric_control', position: 'right', hint: 'Señal de fallo para piloto' },
    ],
  },
  fuse_disconnect: {
    type: 'fuse_disconnect',
    category: 'electrical',
    name: 'Seccionador Portafusibles de Maniobra',
    description: 'Cartucho fusible cilíndrico gG / aM para protección ultrarrápida contra cortocircuitos.',
    defaultLabel: 'Fusibles',
    defaultTagPrefix: 'FU1',
    dimensions: { width: 90, height: 95 },
    defaultSpecs: { fuseRatingA: 6.0 },
    ports: [
      { id: 'line_in', name: 'Entrada Fusible', shortCode: '1', kind: 'electric_power', position: 'top', hint: 'Llegada de tensión' },
      { id: 'load_out', name: 'Salida Protegida Fusible', shortCode: '2', kind: 'electric_power', position: 'bottom', hint: 'Salida protegida hacia transformador o maniobra' },
    ],
  },
  thermal_overload_relay: {
    type: 'thermal_overload_relay',
    category: 'electrical',
    name: 'Relé Térmico de Sobrecarga (Bimetálico)',
    description: 'Relé de protección acoplado al contactor con contactos auxiliares 95-96 (NC de disparo) y 97-98 (NO de señalización).',
    defaultLabel: 'Relé Térmico',
    defaultTagPrefix: 'FR1',
    dimensions: { width: 110, height: 110 },
    defaultSpecs: { overloadCurrentSettingA: 12.0 },
    ports: [
      { id: 'power_in', name: 'Entrada Fuerza (desde contactor)', shortCode: '1-3-5', kind: 'electric_power', position: 'top', hint: 'Conexión a bornes de contactor KM' },
      { id: 'power_out', name: 'Salida a Motor (U-V-W)', shortCode: '2-4-6', kind: 'electric_power', position: 'bottom', hint: 'Hacia bornes de motor' },
      { id: 'aux_nc', name: 'Contacto Disparo NC (95-96)', shortCode: '95-96', kind: 'electric_control', position: 'left', hint: 'Abre la bobina del contactor en sobrecarga' },
      { id: 'aux_no', name: 'Contacto Alarma NO (97-98)', shortCode: '97-98', kind: 'electric_control', position: 'right', hint: 'Enciende piloto rojo de avería térmica' },
    ],
  },

  // --- INSTALACIÓN ELÉCTRICA: MANIOBRA, CONTACTOS Y PULSADORES ---
  contactor_relay: {
    type: 'contactor_relay',
    category: 'electrical',
    name: 'Contactor de Potencia (KM)',
    description: 'Aparato electromagnético de conexión de motores con 3 polos de fuerza, contacto auxiliar NO y bobina A1-A2.',
    defaultLabel: 'Contactor KM',
    defaultTagPrefix: 'KM1',
    dimensions: { width: 105, height: 110 },
    defaultSpecs: { powerKw: 7.5, voltageV: 230 },
    ports: [
      { id: 'line_in', name: 'Contactos Principales L1-L2-L3', shortCode: '1-3-5', kind: 'electric_power', position: 'top', hint: 'Llegada de red de fuerza' },
      { id: 'load_out', name: 'Salida de Potencia T1-T2-T3', shortCode: '2-4-6', kind: 'electric_power', position: 'bottom', hint: 'Salida hacia motor o térmico' },
      { id: 'coil_a1', name: 'Bobina A1 (Fase Maniobra)', shortCode: 'A1', kind: 'electric_control', position: 'left', hint: 'Entrada señal de activación de contactor' },
      { id: 'coil_a2', name: 'Bobina A2 (Neutro Maniobra)', shortCode: 'A2', kind: 'electric_control', position: 'right', hint: 'Neutro o común de maniobra' },
    ],
  },
  relay_coil_auxiliary: {
    type: 'relay_coil_auxiliary',
    category: 'electrical',
    name: 'Relé Auxiliar de Mando (KA / Relé Octal)',
    description: 'Relé electromagnético para multiplicación de contactos y separación galvánica en circuitos de control.',
    defaultLabel: 'Relé Mando KA',
    defaultTagPrefix: 'KA1',
    dimensions: { width: 95, height: 95 },
    defaultSpecs: { coilVoltageV: 230 },
    ports: [
      { id: 'coil_a1', name: 'Bobina A1 (+)', shortCode: 'A1', kind: 'electric_control', position: 'top', hint: 'Alimentación de bobina' },
      { id: 'coil_a2', name: 'Bobina A2 (-)', shortCode: 'A2', kind: 'electric_control', position: 'bottom', hint: 'Retorno de neutro' },
      { id: 'contact_c', name: 'Común Contacto (11)', shortCode: '11', kind: 'electric_control', position: 'left', hint: 'Borne común inversor' },
      { id: 'contact_no', name: 'Contacto Abierto (14)', shortCode: '14', kind: 'electric_control', position: 'right', hint: 'Contacto normalmente abierto' },
    ],
  },
  contact_aux_no: {
    type: 'contact_aux_no',
    category: 'electrical',
    name: 'Contacto Auxiliar Abierto (NO 13-14)',
    description: 'Contacto normalmente abierto para autoenclavamiento (retención) o encendido de señalizaciones.',
    defaultLabel: 'Contacto NO',
    defaultTagPrefix: '13-14',
    dimensions: { width: 85, height: 75 },
    defaultSpecs: { contactState: 'open' },
    ports: [
      { id: 'term_13', name: 'Borne 13 Entrada', shortCode: '13', kind: 'electric_control', position: 'top', hint: 'Entrada de maniobra' },
      { id: 'term_14', name: 'Borne 14 Salida', shortCode: '14', kind: 'electric_control', position: 'bottom', hint: 'Salida de maniobra' },
    ],
  },
  contact_aux_nc: {
    type: 'contact_aux_nc',
    category: 'electrical',
    name: 'Contacto Auxiliar Cerrado (NC 21-22)',
    description: 'Contacto normalmente cerrado para enclavamiento eléctrico mutuo (evitar inversión de giro simultánea).',
    defaultLabel: 'Contacto NC',
    defaultTagPrefix: '21-22',
    dimensions: { width: 85, height: 75 },
    defaultSpecs: { contactState: 'closed' },
    ports: [
      { id: 'term_21', name: 'Borne 21 Entrada', shortCode: '21', kind: 'electric_control', position: 'top', hint: 'Entrada de seguridad' },
      { id: 'term_22', name: 'Borne 22 Salida', shortCode: '22', kind: 'electric_control', position: 'bottom', hint: 'Salida de seguridad hacia bobina rival' },
    ],
  },
  timer_delay_on: {
    type: 'timer_delay_on',
    category: 'electrical',
    name: 'Temporizador al Trabajo (Retardo Conexión TON)',
    description: 'Relé de tiempo que retrasa el cierre de su contacto (anti-ciclo corto de compresor o secuencia escalonada).',
    defaultLabel: 'Temporizador TON',
    defaultTagPrefix: 'KT1',
    dimensions: { width: 100, height: 100 },
    defaultSpecs: { timerDelayS: 180 },
    ports: [
      { id: 'coil_a1', name: 'Alimentación A1', shortCode: 'A1', kind: 'electric_control', position: 'top', hint: 'Tensión de control' },
      { id: 'coil_a2', name: 'Alimentación A2', shortCode: 'A2', kind: 'electric_control', position: 'bottom', hint: 'Neutro de control' },
      { id: 'contact_no', name: 'Contacto Temporizado (17-18)', shortCode: '17-18', kind: 'electric_control', position: 'right', hint: 'Cierra tras transcurrir el tiempo' },
    ],
  },
  timer_delay_off: {
    type: 'timer_delay_off',
    category: 'electrical',
    name: 'Temporizador al Reposo (Retardo Desconexión TOFF)',
    description: 'Mantiene activada la carga durante un tiempo tras desaparecer la señal de mando (ej. barrido de ventilador).',
    defaultLabel: 'Temporizador TOFF',
    defaultTagPrefix: 'KT2',
    dimensions: { width: 100, height: 100 },
    defaultSpecs: { timerDelayS: 60 },
    ports: [
      { id: 'coil_a1', name: 'Alimentación A1', shortCode: 'A1', kind: 'electric_control', position: 'top', hint: 'Alimentación permanente' },
      { id: 'control_y1', name: 'Trigger Disparo Y1', shortCode: 'Y1', kind: 'electric_control', position: 'left', hint: 'Señal de entrada de temporización' },
      { id: 'contact_out', name: 'Contacto Salida (15-18)', shortCode: '15-18', kind: 'electric_control', position: 'right', hint: 'Permanece cerrado hasta finalizar el retardo' },
      { id: 'coil_a2', name: 'Neutro A2', shortCode: 'A2', kind: 'electric_control', position: 'bottom', hint: 'Neutro' },
    ],
  },
  pushbutton_no: {
    type: 'pushbutton_no',
    category: 'electrical',
    name: 'Pulsador de Marcha NO (Verde / Start)',
    description: 'Pulsador normalmente abierto (bornes 3-4) para arranque manual de maniobra con retorno por muelle.',
    defaultLabel: 'Pulsador Marcha',
    defaultTagPrefix: 'SB1',
    dimensions: { width: 85, height: 90 },
    defaultSpecs: { isPushButtonPressed: false },
    ports: [
      { id: 'term_3', name: 'Borne Entrada 3', shortCode: '3', kind: 'electric_control', position: 'top', hint: 'Llegada de fase de control' },
      { id: 'term_4', name: 'Borne Salida 4', shortCode: '4', kind: 'electric_control', position: 'bottom', hint: 'Hacia bobina contactor y contacto 14' },
    ],
  },
  pushbutton_nc: {
    type: 'pushbutton_nc',
    category: 'electrical',
    name: 'Pulsador de Paro NC (Rojo / Stop)',
    description: 'Pulsador normalmente cerrado (bornes 1-2) para parada de la maniobra al cortar la alimentación.',
    defaultLabel: 'Pulsador Paro',
    defaultTagPrefix: 'SB2',
    dimensions: { width: 85, height: 90 },
    defaultSpecs: { isPushButtonPressed: false },
    ports: [
      { id: 'term_1', name: 'Borne Entrada 1', shortCode: '1', kind: 'electric_control', position: 'top', hint: 'Llegada de fase de seguridad' },
      { id: 'term_2', name: 'Borne Salida 2', shortCode: '2', kind: 'electric_control', position: 'bottom', hint: 'Hacia pulsador de marcha' },
    ],
  },
  emergency_stop_button: {
    type: 'emergency_stop_button',
    category: 'electrical',
    name: 'Seta de Parada de Emergencia (Enclavamiento)',
    description: 'Pulsador de seguridad tipo seta con retención mecánica y contactos de apertura positiva NC.',
    defaultLabel: 'Seta Emergencia',
    defaultTagPrefix: 'SE1',
    dimensions: { width: 95, height: 100 },
    defaultSpecs: { isPushButtonPressed: false },
    ports: [
      { id: 'term_1', name: 'Línea Seguridad Entrada', shortCode: '11', kind: 'electric_control', position: 'top', hint: 'Entrada del lazo de emergencia' },
      { id: 'term_2', name: 'Línea Seguridad Salida', shortCode: '12', kind: 'electric_control', position: 'bottom', hint: 'Corte de todo el circuito de maniobra' },
    ],
  },
  selector_switch_rotary: {
    type: 'selector_switch_rotary',
    category: 'electrical',
    name: 'Selector de Mando (Man - 0 - Auto)',
    description: 'Interruptor giratorio de 3 posiciones para selección entre modo manual, apagado o control automático por termostato.',
    defaultLabel: 'Selector Man-0-Auto',
    defaultTagPrefix: 'SA1',
    dimensions: { width: 95, height: 95 },
    defaultSpecs: { selectorPosition: 'auto' },
    ports: [
      { id: 'common_in', name: 'Común Entrada', shortCode: 'C', kind: 'electric_control', position: 'top', hint: 'Fase de maniobra común' },
      { id: 'manual_out', name: 'Posición Manual', shortCode: 'MAN', kind: 'electric_control', position: 'left', hint: 'Salida directa a marcha manual' },
      { id: 'auto_out', name: 'Posición Automática', shortCode: 'AUTO', kind: 'electric_control', position: 'right', hint: 'Hacia termostato / presostato' },
    ],
  },

  // --- INSTALACIÓN ELÉCTRICA: TRANSFORMADORES Y FUENTES ---
  control_transformer: {
    type: 'control_transformer',
    category: 'electrical',
    name: 'Transformador de Maniobra (400V/230V a 24V AC)',
    description: 'Transformador de aislamiento galvánico para alimentar la maniobra a tensión de seguridad de 24V AC.',
    defaultLabel: 'Transformador',
    defaultTagPrefix: 'TC1',
    dimensions: { width: 100, height: 100 },
    defaultSpecs: { powerKw: 0.25, voltageV: 230 },
    ports: [
      { id: 'pri_1', name: 'Primario 230V L', shortCode: 'PRI-L', kind: 'electric_power', position: 'top', hint: 'Entrada primaria 230V' },
      { id: 'pri_2', name: 'Primario 230V N', shortCode: 'PRI-N', kind: 'electric_neutral', position: 'left', hint: 'Neutro primario' },
      { id: 'sec_1', name: 'Secundario 24V ~', shortCode: 'SEC-1', kind: 'electric_control', position: 'bottom', hint: 'Salida 24V AC para maniobra' },
      { id: 'sec_2', name: 'Secundario 24V Común', shortCode: 'SEC-2', kind: 'electric_control', position: 'right', hint: 'Retorno 24V AC' },
    ],
  },
  power_supply_dc_24v: {
    type: 'power_supply_dc_24v',
    category: 'electrical',
    name: 'Fuente de Alimentación Conmutada (24V DC)',
    description: 'Fuente estabilizada para alimentación de controladores digitales, autómatas, sondas electrónicas y EEV.',
    defaultLabel: 'Fuente 24V DC',
    defaultTagPrefix: 'PS1',
    dimensions: { width: 100, height: 105 },
    defaultSpecs: { powerKw: 0.12, voltageV: 24 },
    ports: [
      { id: 'ac_l', name: 'Entrada AC (L)', shortCode: 'L', kind: 'electric_power', position: 'top', hint: 'Llegada de fase 230V' },
      { id: 'ac_n', name: 'Entrada AC (N)', shortCode: 'N', kind: 'electric_neutral', position: 'left', hint: 'Llegada de neutro' },
      { id: 'dc_plus', name: 'Salida +24V DC', shortCode: '+24V', kind: 'electric_control', position: 'bottom', hint: 'Positivo 24V DC' },
      { id: 'dc_minus', name: 'Salida 0V (GND)', shortCode: '0V', kind: 'electric_neutral', position: 'right', hint: 'Masa / Común 0V DC' },
    ],
  },

  // --- INSTALACIÓN ELÉCTRICA: SEÑALIZACIÓN Y AVISADORES ---
  pilot_light_green: {
    type: 'pilot_light_green',
    category: 'electrical',
    name: 'Piloto Señalización Verde (Marcha)',
    description: 'Lámpara de señalización LED verde para indicar estado en funcionamiento de compresor o ventiladores.',
    defaultLabel: 'Piloto Marcha',
    defaultTagPrefix: 'HL1',
    dimensions: { width: 75, height: 80 },
    defaultSpecs: { pilotLightColor: 'green' },
    ports: [
      { id: 'term_x1', name: 'Borne X1 (+)', shortCode: 'X1', kind: 'electric_control', position: 'top', hint: 'Llegada desde contacto KM 13-14' },
      { id: 'term_x2', name: 'Borne X2 (Neutro)', shortCode: 'X2', kind: 'electric_neutral', position: 'bottom', hint: 'Retorno a neutro' },
    ],
  },
  pilot_light_red: {
    type: 'pilot_light_red',
    category: 'electrical',
    name: 'Piloto Señalización Rojo (Avería / Disparo Térmico)',
    description: 'Lámpara indicadora de parada por avería, disparo del relé térmico 97-98 o alarma de alta presión.',
    defaultLabel: 'Piloto Avería',
    defaultTagPrefix: 'HL2',
    dimensions: { width: 75, height: 80 },
    defaultSpecs: { pilotLightColor: 'red' },
    ports: [
      { id: 'term_x1', name: 'Borne X1 (+)', shortCode: 'X1', kind: 'electric_control', position: 'top', hint: 'Llegada desde contacto de alarma' },
      { id: 'term_x2', name: 'Borne X2 (Neutro)', shortCode: 'X2', kind: 'electric_neutral', position: 'bottom', hint: 'Retorno a neutro' },
    ],
  },
  pilot_light_amber: {
    type: 'pilot_light_amber',
    category: 'electrical',
    name: 'Piloto Señalización Ámbar (Tensión / Espera)',
    description: 'Lámpara LED ámbar para indicar presencia de tensión de red o ciclo de recogida pump-down.',
    defaultLabel: 'Piloto Tensión',
    defaultTagPrefix: 'HL3',
    dimensions: { width: 75, height: 80 },
    defaultSpecs: { pilotLightColor: 'amber' },
    ports: [
      { id: 'term_x1', name: 'Borne X1 (+)', shortCode: 'X1', kind: 'electric_control', position: 'top', hint: 'Fase' },
      { id: 'term_x2', name: 'Borne X2 (N)', shortCode: 'X2', kind: 'electric_neutral', position: 'bottom', hint: 'Neutro' },
    ],
  },
  buzzer_siren: {
    type: 'buzzer_siren',
    category: 'electrical',
    name: 'Avisador Acústico / Sirena de Alarma',
    description: 'Zumbador piezoeléctrico de alarma sonora ante fugas de gas, fallo térmico o sobrepresión.',
    defaultLabel: 'Bocina Alarma',
    defaultTagPrefix: 'HA1',
    dimensions: { width: 85, height: 85 },
    defaultSpecs: {},
    ports: [
      { id: 'term_plus', name: 'Alimentación Alarma (+)', shortCode: '+', kind: 'electric_control', position: 'top', hint: 'Señal activada en disparo' },
      { id: 'term_minus', name: 'Neutro / Común (-)', shortCode: '-', kind: 'electric_neutral', position: 'bottom', hint: 'Retorno' },
    ],
  },

  // --- INSTALACIÓN ELÉCTRICA: CARGAS, MOTORES Y ELECTRÓNICA ---
  electric_motor_3p: {
    type: 'electric_motor_3p',
    category: 'electrical',
    name: 'Motor Eléctrico Trifásico (M 3~)',
    description: 'Motor asíncrono trifásico para compresores abiertos, bombas de salmuera o ventiladores axiales de condensador.',
    defaultLabel: 'Motor Trifásico',
    defaultTagPrefix: 'M1',
    dimensions: { width: 105, height: 110 },
    defaultSpecs: { powerKw: 5.5, ratedCurrentA: 11.2 },
    ports: [
      { id: 'term_u1', name: 'Borne U1 (Fase 1)', shortCode: 'U1', kind: 'electric_power', position: 'top', hint: 'Conexión fase L1' },
      { id: 'term_v1', name: 'Borne V1 (Fase 2)', shortCode: 'V1', kind: 'electric_power', position: 'left', hint: 'Conexión fase L2' },
      { id: 'term_w1', name: 'Borne W1 (Fase 3)', shortCode: 'W1', kind: 'electric_power', position: 'right', hint: 'Conexión fase L3' },
      { id: 'term_pe', name: 'Toma Tierra (PE)', shortCode: 'PE', kind: 'electric_ground', position: 'bottom', hint: 'Puesta a tierra del chasis del motor' },
    ],
  },
  electric_motor_1p: {
    type: 'electric_motor_1p',
    category: 'electrical',
    name: 'Motor Eléctrico Monofásico (M 1~)',
    description: 'Motor monofásico con condensador permanente de arranque para ventiladores de evaporador y bombas pequeñas.',
    defaultLabel: 'Motor Monofásico',
    defaultTagPrefix: 'M2',
    dimensions: { width: 95, height: 100 },
    defaultSpecs: { powerKw: 0.75, ratedCurrentA: 4.8 },
    ports: [
      { id: 'term_l', name: 'Fase de Trabajo (L)', shortCode: 'L', kind: 'electric_power', position: 'top', hint: 'Alimentación 230V' },
      { id: 'term_n', name: 'Neutro (N)', shortCode: 'N', kind: 'electric_neutral', position: 'bottom', hint: 'Neutro' },
      { id: 'term_pe', name: 'Tierra Chasis (PE)', shortCode: 'PE', kind: 'electric_ground', position: 'left', hint: 'Tierra' },
    ],
  },
  electric_heater: {
    type: 'electric_heater',
    category: 'electrical',
    name: 'Resistencia Eléctrica de Desescarche / Cárter',
    description: 'Elemento calefactor blindado para descongelar baterías de evaporador o mantener caliente el cárter en paradas.',
    defaultLabel: 'Resistencia Eléctrica',
    defaultTagPrefix: 'EH1',
    dimensions: { width: 105, height: 85 },
    defaultSpecs: { powerKw: 3.0, voltageV: 230 },
    ports: [
      { id: 'term_l', name: 'Fase Calefactor (1)', shortCode: '1', kind: 'electric_power', position: 'left', hint: 'Alimentación desde contactor de desescarche' },
      { id: 'term_n', name: 'Neutro Calefactor (2)', shortCode: '2', kind: 'electric_neutral', position: 'right', hint: 'Retorno de neutro' },
      { id: 'term_pe', name: 'Tierra Blindaje (PE)', shortCode: 'PE', kind: 'electric_ground', position: 'bottom', hint: 'Puesta a tierra de protección' },
    ],
  },
  solenoid_coil: {
    type: 'solenoid_coil',
    category: 'electrical',
    name: 'Bobina Eléctrica Solenoide (Y1)',
    description: 'Actuador electromagnético para apertura/cierre de la válvula de solenoide de línea de líquido.',
    defaultLabel: 'Bobina Solenoide',
    defaultTagPrefix: 'Y1',
    dimensions: { width: 90, height: 85 },
    defaultSpecs: { powerKw: 0.02, voltageV: 230 },
    ports: [
      { id: 'term_1', name: 'Fase Bobina Solenoide', shortCode: '1', kind: 'electric_control', position: 'top', hint: 'Conexión desde salida del termostato' },
      { id: 'term_2', name: 'Neutro Bobina', shortCode: '2', kind: 'electric_neutral', position: 'bottom', hint: 'Neutro de maniobra' },
    ],
  },
  frequency_inverter_vfd: {
    type: 'frequency_inverter_vfd',
    category: 'electrical',
    name: 'Variador de Frecuencia (Inverter VFD)',
    description: 'Controlador de velocidad variable para regulación continua de capacidad y optimización energética.',
    defaultLabel: 'Variador Inverter',
    defaultTagPrefix: 'VFD-01',
    dimensions: { width: 115, height: 120 },
    defaultSpecs: {
      frequencyHz: 50.0,
      powerKw: 11.0,
    },
    ports: [
      { id: 'mains_in', name: 'Entrada Alimentación AC', shortCode: 'AC-IN', kind: 'electric_power', position: 'top', hint: 'Llegada de corriente alterna desde disyuntor' },
      { id: 'motor_out', name: 'Salida Modulada PWM', shortCode: 'U-V-W', kind: 'electric_power', position: 'bottom', hint: 'Alimentación variable al compresor inverter' },
      { id: 'speed_ref', name: 'Consigna Analógica 0-10V', shortCode: '0-10V', kind: 'electric_signal', position: 'left', hint: 'Señal de modulación de presión de aspiración' },
    ],
  },
  soft_starter: {
    type: 'soft_starter',
    category: 'electrical',
    name: 'Arrancador Suave Electrónico',
    description: 'Controlador por tiristores para arranque suave sin picos de corriente destructivos en la red.',
    defaultLabel: 'Arrancador Suave',
    defaultTagPrefix: 'SS-01',
    dimensions: { width: 110, height: 115 },
    defaultSpecs: {
      powerKw: 15.0,
    },
    ports: [
      { id: 'line_in', name: 'Línea de Entrada', shortCode: 'L-IN', kind: 'electric_power', position: 'top', hint: 'Entrada de alimentación trifásica' },
      { id: 'motor_out', name: 'Salida Suave al Motor', shortCode: 'M-OUT', kind: 'electric_power', position: 'bottom', hint: 'Tensión progresiva de rampa de arranque' },
    ],
  },
  power_demand_controller: {
    type: 'power_demand_controller',
    category: 'electrical',
    name: 'Controlador de Demanda & Maxímetro',
    description: 'Monitor de potencia de red para optimización de costes y deslastre inteligente de compresores.',
    defaultLabel: 'Controlador Demanda',
    defaultTagPrefix: 'PDC-01',
    dimensions: { width: 115, height: 115 },
    defaultSpecs: {
      demandLimitKw: 35.0,
      maxContractedPowerKw: 45.0,
    },
    ports: [
      { id: 'meter_ct', name: 'Medición Transformadores TI', shortCode: 'TI-CT', kind: 'electric_signal', position: 'top', hint: 'Lectura de amperios en tiempo real' },
      { id: 'shed_out', name: 'Salida Deslastre de Cargas', shortCode: 'DESL', kind: 'electric_control', position: 'bottom', hint: 'Contacto de bloqueo para compresores secundarios' },
    ],
  },

  // --- ELECTRICIDAD BÁSICA & DIDÁCTICA (CIRCUITOS ELEMENTALES) ---
  battery_dc_cell: {
    type: 'battery_dc_cell',
    category: 'basic_electrical',
    name: 'Batería / Pila DC',
    description: 'Fuente de corriente continua (DC). Proporciona tensión constante entre su polo positivo y negativo.',
    defaultLabel: 'Batería 12V',
    defaultTagPrefix: 'BAT-01',
    dimensions: { width: 100, height: 95 },
    defaultSpecs: {
      voltageV: 12.0,
      isEnergized: true,
    },
    ports: [
      { id: 'pos', name: 'Polo Positivo (+)', shortCode: '+', kind: 'electric_power', position: 'top', hint: 'Borne Positivo (+12V DC)' },
      { id: 'neg', name: 'Polo Negativo (-)', shortCode: '-', kind: 'electric_neutral', position: 'bottom', hint: 'Borne Negativo (Masa / 0V DC)' },
    ],
  },
  power_source_ac: {
    type: 'power_source_ac',
    category: 'basic_electrical',
    name: 'Fuente de Alimentación AC',
    description: 'Generador o red eléctrica de corriente alterna monofásica (Fase y Neutro).',
    defaultLabel: 'Fuente 230V AC',
    defaultTagPrefix: 'VAC-01',
    dimensions: { width: 105, height: 95 },
    defaultSpecs: {
      voltageV: 230.0,
      frequencyHz: 50.0,
      isEnergized: true,
    },
    ports: [
      { id: 'phase', name: 'Fase (L)', shortCode: 'L', kind: 'electric_power', position: 'top', hint: 'Línea de Fase activa (230V AC)' },
      { id: 'neutral', name: 'Neutro (N)', shortCode: 'N', kind: 'electric_neutral', position: 'bottom', hint: 'Conductor neutro de retorno (0V)' },
    ],
  },
  light_bulb: {
    type: 'light_bulb',
    category: 'basic_electrical',
    name: 'Bombilla Incandescente / Lámpara',
    description: 'Carga luminosa. Se ilumina radiantemente cuando circula corriente a través de un circuito cerrado.',
    defaultLabel: 'Bombilla',
    defaultTagPrefix: 'LMP-01',
    dimensions: { width: 95, height: 105 },
    defaultSpecs: {
      voltageV: 12.0,
      powerKw: 0.06,
      isEnergized: false,
    },
    ports: [
      { id: 'terminal_1', name: 'Borne 1', shortCode: 'T1', kind: 'electric_power', position: 'left', hint: 'Terminal de entrada de corriente (+ / Fase)' },
      { id: 'terminal_2', name: 'Borne 2', shortCode: 'T2', kind: 'electric_neutral', position: 'right', hint: 'Terminal de salida hacia masa (- / Neutro)' },
    ],
  },
  switch_spst: {
    type: 'switch_spst',
    category: 'basic_electrical',
    name: 'Interruptor Unipolar (SPST)',
    description: 'Interruptor basculante básico. Permite abrir o cerrar manualmente el circuito eléctrico.',
    defaultLabel: 'Interruptor',
    defaultTagPrefix: 'SW-01',
    dimensions: { width: 95, height: 90 },
    defaultSpecs: {
      isSwitchClosed: false,
      isEnergized: false,
    },
    ports: [
      { id: 'in', name: 'Borne Entrada', shortCode: '1', kind: 'electric_power', position: 'left', hint: 'Entrada de corriente al interruptor' },
      { id: 'out', name: 'Borne Salida', shortCode: '2', kind: 'electric_power', position: 'right', hint: 'Salida conmutada hacia la carga' },
    ],
  },
  switch_spdt: {
    type: 'switch_spdt',
    category: 'basic_electrical',
    name: 'Conmutador Unipolar (SPDT)',
    description: 'Conmutador de 2 posiciones. Permite desviar la corriente entre dos circuitos distintos.',
    defaultLabel: 'Conmutador',
    defaultTagPrefix: 'SW-COM',
    dimensions: { width: 100, height: 95 },
    defaultSpecs: {
      selectorPosition: 'man',
      isEnergized: false,
    },
    ports: [
      { id: 'common', name: 'Borne Común', shortCode: 'COM', kind: 'electric_power', position: 'left', hint: 'Borne Común de entrada' },
      { id: 'l1', name: 'Posición 1', shortCode: '1', kind: 'electric_power', position: 'top', hint: 'Contacto de conmutación 1' },
      { id: 'l2', name: 'Posición 2', shortCode: '2', kind: 'electric_power', position: 'bottom', hint: 'Contacto de conmutación 2' },
    ],
  },
  pushbutton_simple: {
    type: 'pushbutton_simple',
    category: 'basic_electrical',
    name: 'Pulsador Normalmente Abierto (NO)',
    description: 'Pulsador momentáneo. Conduce únicamente mientras permanece presionado.',
    defaultLabel: 'Pulsador NO',
    defaultTagPrefix: 'PB-NO',
    dimensions: { width: 95, height: 90 },
    defaultSpecs: {
      isPushButtonPressed: false,
      isSwitchClosed: false,
    },
    ports: [
      { id: 'in', name: 'Contacto 13', shortCode: '13', kind: 'electric_power', position: 'left', hint: 'Entrada de contacto normalmente abierto' },
      { id: 'out', name: 'Contacto 14', shortCode: '14', kind: 'electric_power', position: 'right', hint: 'Salida de contacto normalmente abierto' },
    ],
  },
  pushbutton_nc_simple: {
    type: 'pushbutton_nc_simple',
    category: 'basic_electrical',
    name: 'Pulsador Normalmente Cerrado (NC)',
    description: 'Pulsador de parada/apertura. Interrumpe la corriente al ser accionado.',
    defaultLabel: 'Pulsador NC',
    defaultTagPrefix: 'PB-NC',
    dimensions: { width: 95, height: 90 },
    defaultSpecs: {
      isPushButtonPressed: false,
      isSwitchClosed: true,
    },
    ports: [
      { id: 'in', name: 'Contacto 11', shortCode: '11', kind: 'electric_power', position: 'left', hint: 'Entrada de contacto normalmente cerrado' },
      { id: 'out', name: 'Contacto 12', shortCode: '12', kind: 'electric_power', position: 'right', hint: 'Salida de contacto normalmente cerrado' },
    ],
  },
  resistor_fixed: {
    type: 'resistor_fixed',
    category: 'basic_electrical',
    name: 'Resistencia Fija',
    description: 'Componente pasivo lineal que limita la intensidad de corriente según la ley de Ohm (V = I · R).',
    defaultLabel: 'Resistencia 100Ω',
    defaultTagPrefix: 'R-01',
    dimensions: { width: 100, height: 85 },
    defaultSpecs: {
      resistanceOhm: 100.0,
      powerKw: 0.005,
    },
    ports: [
      { id: 't1', name: 'Terminal A', shortCode: 'A', kind: 'electric_power', position: 'left', hint: 'Extremo A de la resistencia' },
      { id: 't2', name: 'Terminal B', shortCode: 'B', kind: 'electric_power', position: 'right', hint: 'Extremo B de la resistencia' },
    ],
  },
  potentiometer: {
    type: 'potentiometer',
    category: 'basic_electrical',
    name: 'Potenciómetro / Resistencia Variable',
    description: 'Resistencia con toma intermedia ajustable mediante cursor móvil.',
    defaultLabel: 'Potenciómetro 10kΩ',
    defaultTagPrefix: 'POT-01',
    dimensions: { width: 105, height: 95 },
    defaultSpecs: {
      resistanceOhm: 10000.0,
      openingPercent: 50.0,
    },
    ports: [
      { id: 't1', name: 'Extremo 1', shortCode: '1', kind: 'electric_power', position: 'left', hint: 'Terminal fijo inferior' },
      { id: 'wiper', name: 'Cursor Móvil', shortCode: 'W', kind: 'electric_power', position: 'top', hint: 'Terminal móvil de tensión regulada' },
      { id: 't2', name: 'Extremo 2', shortCode: '2', kind: 'electric_power', position: 'right', hint: 'Terminal fijo superior' },
    ],
  },
  capacitor_fixed: {
    type: 'capacitor_fixed',
    category: 'basic_electrical',
    name: 'Condensador / Capacitor',
    description: 'Almacena carga eléctrica en un campo electrostático entre sus placas conductoras.',
    defaultLabel: 'Condensador 100µF',
    defaultTagPrefix: 'CAP-01',
    dimensions: { width: 95, height: 85 },
    defaultSpecs: {
      capacitanceUf: 100.0,
      voltageV: 25.0,
    },
    ports: [
      { id: 'pos', name: 'Polo Positivo (+)', shortCode: '+', kind: 'electric_power', position: 'left', hint: 'Placa ánodo (+)' },
      { id: 'neg', name: 'Polo Negativo (-)', shortCode: '-', kind: 'electric_neutral', position: 'right', hint: 'Placa cátodo (-)' },
    ],
  },
  diode_led: {
    type: 'diode_led',
    category: 'basic_electrical',
    name: 'Diodo Emisor de Luz (LED)',
    description: 'Semiconductor que emite luz cuando está polarizado en sentido directo (Ánodo a + y Cátodo a -).',
    defaultLabel: 'Diodo LED',
    defaultTagPrefix: 'LED-01',
    dimensions: { width: 95, height: 95 },
    defaultSpecs: {
      pilotLightColor: 'green',
      voltageV: 2.2,
      isEnergized: false,
    },
    ports: [
      { id: 'anode', name: 'Ánodo (+)', shortCode: 'A(+)', kind: 'electric_power', position: 'left', hint: 'Terminal Ánodo (conectar al polo positivo +)' },
      { id: 'cathode', name: 'Cátodo (-)', shortCode: 'K(-)', kind: 'electric_neutral', position: 'right', hint: 'Terminal Cátodo (conectar al polo negativo -)' },
    ],
  },
  voltmeter_basic: {
    type: 'voltmeter_basic',
    category: 'basic_electrical',
    name: 'Voltímetro Digital',
    description: 'Instrumento de alta impedancia para medir la diferencia de potencial (Voltios) entre dos puntos en paralelo.',
    defaultLabel: 'Voltímetro',
    defaultTagPrefix: 'VM-01',
    dimensions: { width: 95, height: 95 },
    defaultSpecs: {
      measuredValue: 0.0,
      measuredUnit: 'V',
    },
    ports: [
      { id: 'v_pos', name: 'Punta Positiva (+)', shortCode: 'V(+)', kind: 'electric_power', position: 'left', hint: 'Punta de prueba positiva (+)' },
      { id: 'v_com', name: 'Punta COM (-)', shortCode: 'COM', kind: 'electric_neutral', position: 'right', hint: 'Punta de prueba común / negativo (-)' },
    ],
  },
  ammeter_basic: {
    type: 'ammeter_basic',
    category: 'basic_electrical',
    name: 'Amperímetro Digital',
    description: 'Instrumento de bajísima resistencia interna conectado en serie para medir la corriente (Amperios).',
    defaultLabel: 'Amperímetro',
    defaultTagPrefix: 'AM-01',
    dimensions: { width: 95, height: 95 },
    defaultSpecs: {
      measuredValue: 0.0,
      measuredUnit: 'A',
    },
    ports: [
      { id: 'a_in', name: 'Entrada Serie', shortCode: 'A_IN', kind: 'electric_power', position: 'left', hint: 'Entrada de corriente en serie' },
      { id: 'a_out', name: 'Salida Serie', shortCode: 'A_OUT', kind: 'electric_power', position: 'right', hint: 'Salida de corriente hacia el circuito' },
    ],
  },
  cell_dc_simple: {
    type: 'cell_dc_simple',
    category: 'basic_electrical',
    name: 'Pila Cilíndrica (1.5V / 9V)',
    description: 'Pila electroquímica individual para circuitos didácticos elementales.',
    defaultLabel: 'Pila 1.5V',
    defaultTagPrefix: 'PIL-01',
    dimensions: { width: 90, height: 95 },
    defaultSpecs: {
      voltageV: 1.5,
      isEnergized: true,
    },
    ports: [
      { id: 'pos', name: 'Borne (+)', shortCode: '+', kind: 'electric_power', position: 'top', hint: 'Polo Positivo (+)' },
      { id: 'neg', name: 'Borne (-)', shortCode: '-', kind: 'electric_neutral', position: 'bottom', hint: 'Polo Negativo (-)' },
    ],
  },
  dc_power_source: {
    type: 'dc_power_source',
    category: 'basic_electrical',
    name: 'Fuente DC Regulable de Laboratorio',
    description: 'Fuente de corriente continua de laboratorio con ajuste de tensión y limitación de corriente.',
    defaultLabel: 'Fuente DC 0-30V',
    defaultTagPrefix: 'VDC-01',
    dimensions: { width: 110, height: 100 },
    defaultSpecs: {
      voltageV: 24.0,
      isEnergized: true,
    },
    ports: [
      { id: 'pos', name: 'Salida (+)', shortCode: '+', kind: 'electric_power', position: 'top', hint: 'Polo Positivo DC (+)' },
      { id: 'neg', name: 'Salida (-)', shortCode: '-', kind: 'electric_neutral', position: 'bottom', hint: 'Polo Negativo DC (-)' },
    ],
  },
  power_source_ac_3p: {
    type: 'power_source_ac_3p',
    category: 'basic_electrical',
    name: 'Alimentación Alterna Trifásica (3F+N+PE)',
    description: 'Acometida de red trifásica 400V (L1, L2, L3, Neutro N y Tierra PE).',
    defaultLabel: 'Red 400V 3F+N',
    defaultTagPrefix: 'RED-3P',
    dimensions: { width: 120, height: 115 },
    defaultSpecs: {
      voltageV: 400.0,
      frequencyHz: 50.0,
      isEnergized: true,
    },
    ports: [
      { id: 'l1', name: 'Fase L1', shortCode: 'L1', kind: 'electric_power', position: 'top', hint: 'Fase 1 (Marrón)' },
      { id: 'l2', name: 'Fase L2', shortCode: 'L2', kind: 'electric_power', position: 'top', hint: 'Fase 2 (Negro)' },
      { id: 'l3', name: 'Fase L3', shortCode: 'L3', kind: 'electric_power', position: 'top', hint: 'Fase 3 (Gris)' },
      { id: 'neutral', name: 'Neutro N', shortCode: 'N', kind: 'electric_neutral', position: 'bottom', hint: 'Neutro (Azul)' },
      { id: 'pe', name: 'Tierra PE', shortCode: 'PE', kind: 'electric_ground', position: 'bottom', hint: 'Puesta a tierra' },
    ],
  },
  junction_dot_electric: {
    type: 'junction_dot_electric',
    category: 'basic_electrical',
    name: 'Punto de Unión / Nodo de Conexión',
    description: 'Punto equipotencial para derivación limpia y distribución de conductores.',
    defaultLabel: 'Nodo Derivación',
    defaultTagPrefix: 'NOD-01',
    dimensions: { width: 65, height: 65 },
    ports: [
      { id: 'p1', name: 'Borne Norte', shortCode: 'N', kind: 'electric_power', position: 'top', hint: 'Derivación norte' },
      { id: 'p2', name: 'Borne Este', shortCode: 'E', kind: 'electric_power', position: 'right', hint: 'Derivación este' },
      { id: 'p3', name: 'Borne Sur', shortCode: 'S', kind: 'electric_power', position: 'bottom', hint: 'Derivación sur' },
      { id: 'p4', name: 'Borne Oeste', shortCode: 'O', kind: 'electric_power', position: 'left', hint: 'Derivación oeste' },
    ],
  },
  terminal_block_electric: {
    type: 'terminal_block_electric',
    category: 'basic_electrical',
    name: 'Regleta / Bornero de Conexión',
    description: 'Bloque de bornes aislados para conexión y ordenación de cables en cuadro o bastidor.',
    defaultLabel: 'Regleta X1',
    defaultTagPrefix: 'REG-01',
    dimensions: { width: 95, height: 85 },
    ports: [
      { id: 't1', name: 'Borne 1', shortCode: '1', kind: 'electric_power', position: 'left', hint: 'Entrada borne 1' },
      { id: 't2', name: 'Borne 2', shortCode: '2', kind: 'electric_power', position: 'right', hint: 'Salida borne 2' },
      { id: 't3', name: 'Borne 3', shortCode: '3', kind: 'electric_power', position: 'top', hint: 'Puente superior' },
      { id: 't4', name: 'Borne 4', shortCode: '4', kind: 'electric_power', position: 'bottom', hint: 'Puente inferior' },
    ],
  },
  connector_plug_socket: {
    type: 'connector_plug_socket',
    category: 'basic_electrical',
    name: 'Conector / Clavija Desconectable',
    description: 'Base y clavija de conexión rápida enchufable para equipos extraíbles.',
    defaultLabel: 'Conector',
    defaultTagPrefix: 'CON-01',
    dimensions: { width: 90, height: 85 },
    ports: [
      { id: 'in_p', name: 'Entrada (+ / L)', shortCode: 'IN+', kind: 'electric_power', position: 'left', hint: 'Entrada macho polo activo' },
      { id: 'in_n', name: 'Entrada (- / N)', shortCode: 'IN-', kind: 'electric_neutral', position: 'left', hint: 'Entrada macho retorno' },
      { id: 'out_p', name: 'Salida (+ / L)', shortCode: 'OUT+', kind: 'electric_power', position: 'right', hint: 'Salida hembra polo activo' },
      { id: 'out_n', name: 'Salida (- / N)', shortCode: 'OUT-', kind: 'electric_neutral', position: 'right', hint: 'Salida hembra retorno' },
    ],
  },
  neutral_terminal: {
    type: 'neutral_terminal',
    category: 'basic_electrical',
    name: 'Borne Repartidor de Neutro (N)',
    description: 'Pletina repartidora equipotencial para conexión de todos los conductores neutros.',
    defaultLabel: 'Borne Neutro (N)',
    defaultTagPrefix: 'N-BUS',
    dimensions: { width: 85, height: 80 },
    ports: [
      { id: 'n1', name: 'Borne N1', shortCode: 'N1', kind: 'electric_neutral', position: 'left', hint: 'Neutro acometida' },
      { id: 'n2', name: 'Borne N2', shortCode: 'N2', kind: 'electric_neutral', position: 'top', hint: 'Neutro circuito 1' },
      { id: 'n3', name: 'Borne N3', shortCode: 'N3', kind: 'electric_neutral', position: 'right', hint: 'Neutro circuito 2' },
      { id: 'n4', name: 'Borne N4', shortCode: 'N4', kind: 'electric_neutral', position: 'bottom', hint: 'Neutro circuito 3' },
    ],
  },
  switch_disconnector: {
    type: 'switch_disconnector',
    category: 'basic_electrical',
    name: 'Seccionador / Corte en Carga',
    description: 'Aparato mecánico de maniobra que asegura distancia de seccionamiento visible para mantenimiento seguro.',
    defaultLabel: 'Seccionador Q0',
    defaultTagPrefix: 'SEC-01',
    dimensions: { width: 95, height: 95 },
    defaultSpecs: {
      isSwitchClosed: true,
    },
    ports: [
      { id: 'in', name: 'Entrada Línea', shortCode: '1', kind: 'electric_power', position: 'left', hint: 'Llegada de fuerza' },
      { id: 'out', name: 'Salida Carga', shortCode: '2', kind: 'electric_power', position: 'right', hint: 'Salida hacia instalación' },
    ],
  },
  ohmmeter_basic: {
    type: 'ohmmeter_basic',
    category: 'basic_electrical',
    name: 'Ohmímetro Digital',
    description: 'Instrumento para medir la resistencia eléctrica de componentes sin tensión conectada.',
    defaultLabel: 'Ohmímetro',
    defaultTagPrefix: 'OHM-01',
    dimensions: { width: 95, height: 95 },
    defaultSpecs: {
      measuredValue: 0.0,
      measuredUnit: 'Ω',
    },
    ports: [
      { id: 'ohm_1', name: 'Punta Sonda 1', shortCode: 'Ω1', kind: 'electric_power', position: 'left', hint: 'Punta de prueba 1' },
      { id: 'ohm_2', name: 'Punta Sonda 2', shortCode: 'Ω2', kind: 'electric_neutral', position: 'right', hint: 'Punta de prueba 2' },
    ],
  },
  wattmeter_basic: {
    type: 'wattmeter_basic',
    category: 'basic_electrical',
    name: 'Vatímetro Digital (W / kW)',
    description: 'Instrumento para medir la potencia activa absorbida en tiempo real (P = V · I · cos φ).',
    defaultLabel: 'Vatímetro',
    defaultTagPrefix: 'WM-01',
    dimensions: { width: 105, height: 100 },
    defaultSpecs: {
      measuredValue: 0.0,
      measuredUnit: 'W',
    },
    ports: [
      { id: 'v_pos', name: 'Tensión V(+)', shortCode: 'V(+)', kind: 'electric_power', position: 'left', hint: 'Borne de tensión positivo / Fase' },
      { id: 'v_com', name: 'Tensión COM(-)', shortCode: 'COM', kind: 'electric_neutral', position: 'right', hint: 'Borne de tensión negativo / Neutro' },
      { id: 'i_in', name: 'Corriente I_IN', shortCode: 'I_IN', kind: 'electric_power', position: 'top', hint: 'Entrada serie de corriente' },
      { id: 'i_out', name: 'Corriente I_OUT', shortCode: 'I_OUT', kind: 'electric_power', position: 'bottom', hint: 'Salida serie de corriente' },
    ],
  },
};

export const COMPONENT_CATEGORIES: { id: SchematicComponentCategory; label: string; icon: string }[] = [
  { id: 'basic_electrical', label: 'Electricidad Básica & Didáctica', icon: 'Lightbulb' },
  { id: 'electrical', label: 'Instalación Eléctrica Industrial', icon: 'Cpu' },
  { id: 'chambers', label: 'Cámaras Frigoríficas & Recintos', icon: 'Box' },
  { id: 'compressors', label: 'Compresores & Bombas', icon: 'Zap' },
  { id: 'heat_exchangers', label: 'Intercambiadores de Calor', icon: 'Flame' },
  { id: 'expansion', label: 'Expansión & Regulación', icon: 'Gauge' },
  { id: 'vessels', label: 'Recipientes & Aceite', icon: 'Database' },
  { id: 'valves', label: 'Válvulas & Seguridad', icon: 'Sliders' },
  { id: 'fittings', label: 'Uniones & Derivaciones', icon: 'GitFork' },
  { id: 'accessories', label: 'Filtros & Visores', icon: 'Eye' },
  { id: 'instruments', label: 'Instrumentación & Sensores', icon: 'Activity' },
];
