import { SchematicComponentCategory, SchematicComponentDefinition, SchematicComponentType } from '../../../types/schematic';

export const COMPONENT_DEFINITIONS: Record<SchematicComponentType, SchematicComponentDefinition> = {
  // --- COMPRESORES & BOMBAS ---
  compressor_scroll: {
    type: 'compressor_scroll',
    category: 'compressors',
    name: 'Compresor Scroll',
    description: 'Compresor hermético de espiral orbital para aire acondicionado y media temperatura.',
    defaultLabel: 'Compresor Scroll',
    defaultTagPrefix: 'CMP-SCR',
    defaultModel: 'Copeland ZB45KCE',
    dimensions: { width: 120, height: 125 },
    defaultSpecs: {
      powerKw: 7.5,
      displacementM3h: 17.2,
      pressureInBar: 2.1,
      pressureOutBar: 14.5,
      tempInC: -5.0,
      tempOutC: 68.0,
      fluidName: 'R134a',
    },
    ports: [
      { id: 'suction', name: 'Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'left', hint: 'Vapor frío a baja presión proveniente del evaporador / acumulador' },
      { id: 'discharge', name: 'Descarga (HP)', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Gas muy caliente a alta presión hacia el condensador' },
      { id: 'evi', name: 'Inyección EVI / Vapor', shortCode: 'EVI', kind: 'intermediate', position: 'top', hint: 'Puerto para inyección de vapor de economizador a presión intermedia' },
      { id: 'oil_sight', name: 'Cárter de Aceite', shortCode: 'OIL', kind: 'oil', position: 'bottom', hint: 'Conexión para visor, igualación o retorno de aceite al cárter' },
    ],
  },
  compressor_reciprocating: {
    type: 'compressor_reciprocating',
    category: 'compressors',
    name: 'Compresor Alternativo (Pistón)',
    description: 'Compresor semi-hermético de pistones para refrigeración comercial e industrial.',
    defaultLabel: 'Compresor Pistón',
    defaultTagPrefix: 'CMP-REC',
    defaultModel: 'Bitzer 4CES-9Y',
    dimensions: { width: 120, height: 125 },
    defaultSpecs: {
      powerKw: 9.2,
      displacementM3h: 32.5,
      pressureInBar: 1.8,
      pressureOutBar: 15.2,
      tempInC: -8.0,
      tempOutC: 75.0,
    },
    ports: [
      { id: 'suction', name: 'Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'left', hint: 'Vapor frío a baja presión (Entrada a culata de baja)' },
      { id: 'discharge', name: 'Descarga (HP)', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Gas caliente comprimido a alta presión hacia condensador' },
      { id: 'oil_equalization', name: 'Retorno Aceite', shortCode: 'OIL', kind: 'oil', position: 'bottom', hint: 'Línea de compensación y retorno de aceite al cárter' },
    ],
  },
  compressor_screw: {
    type: 'compressor_screw',
    category: 'compressors',
    name: 'Compresor de Tornillo',
    description: 'Compresor de doble rotor helicoidal para grandes enfriadoras y cámaras frigoríficas.',
    defaultLabel: 'Compresor Tornillo',
    defaultTagPrefix: 'CMP-SCW',
    defaultModel: 'Bitzer CSH8573',
    dimensions: { width: 130, height: 120 },
    defaultSpecs: {
      powerKw: 45.0,
      displacementM3h: 180.0,
      capacityKw: 130.0,
      pressureInBar: 2.5,
      pressureOutBar: 16.0,
    },
    ports: [
      { id: 'suction', name: 'Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'left', hint: 'Aspiración de gran caudal de vapor frío' },
      { id: 'discharge', name: 'Descarga (HP)', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Descarga hacia separador de aceite y condensador' },
      { id: 'eco', name: 'Puerto Eco', shortCode: 'ECO', kind: 'intermediate', position: 'top', hint: 'Entrada de economizador para aumento de potencia frigorífica' },
      { id: 'oil_in', name: 'Inyección Aceite', shortCode: 'OIL', kind: 'oil', position: 'bottom', hint: 'Inyección de aceite enfriado para estanqueidad y lubricación' },
    ],
  },
  compressor_inverter: {
    type: 'compressor_inverter',
    category: 'compressors',
    name: 'Compresor Inverter (VFD)',
    description: 'Compresor de velocidad variable modulado por variador de frecuencia (20-90 Hz).',
    defaultLabel: 'Compresor Inverter',
    defaultTagPrefix: 'CMP-INV',
    defaultModel: 'Daikin Variable BLDC',
    dimensions: { width: 120, height: 125 },
    defaultSpecs: {
      powerKw: 5.5,
      frequencyHz: 60,
      cop: 4.2,
      pressureInBar: 2.2,
      pressureOutBar: 14.0,
    },
    ports: [
      { id: 'suction', name: 'Aspiración (LP)', shortCode: 'ASP', kind: 'suction', position: 'left', hint: 'Aspiración modulada en función de la demanda' },
      { id: 'discharge', name: 'Descarga (HP)', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Descarga con control variable de caudal' },
    ],
  },
  compressor_compound: {
    type: 'compressor_compound',
    category: 'compressors',
    name: 'Compresor Compound (2 Etapas)',
    description: 'Compresor de doble etapa en un solo bloque para congelación extrema (-40°C).',
    defaultLabel: 'Compresor Compound',
    defaultTagPrefix: 'CMP-2STG',
    dimensions: { width: 135, height: 125 },
    defaultSpecs: {
      powerKw: 15.0,
      pressureInBar: 0.8,
      pressureOutBar: 15.0,
      capacityKw: 22.0,
    },
    ports: [
      { id: 'lp_suction', name: 'Aspiración Baja', shortCode: 'ASP-BT', kind: 'suction', position: 'left', hint: 'Aspiración de baja presión desde evaporador de congelación' },
      { id: 'inter_discharge', name: 'Intermedia (MP)', shortCode: 'INT', kind: 'intermediate', position: 'top', hint: 'Descarga intermedia hacia enfriador intercooler / subenfriador' },
      { id: 'hp_discharge', name: 'Descarga Alta', shortCode: 'DESC', kind: 'discharge', position: 'right', hint: 'Descarga final a alta presión hacia el condensador' },
    ],
  },
  refrigerant_pump: {
    type: 'refrigerant_pump',
    category: 'compressors',
    name: 'Bomba de Refrigerante Líquido',
    description: 'Bomba centrífuga hermética para recirculación de amoníaco R717 o CO₂ en sistemas inundados.',
    defaultLabel: 'Bomba Refrigerante',
    defaultTagPrefix: 'PUMP-01',
    dimensions: { width: 110, height: 110 },
    defaultSpecs: {
      powerKw: 1.5,
      displacementM3h: 8.5,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'ENT', kind: 'subcooled', position: 'left', hint: 'Alimentación de refrigerante líquido desde el separador de gotas' },
      { id: 'outlet', name: 'Impulsión Líquido', shortCode: 'SAL', kind: 'subcooled', position: 'right', hint: 'Impulsión forzada a los evaporadores inundados' },
    ],
  },

  // --- INTERCAMBIADORES DE CALOR ---
  condenser_air: {
    type: 'condenser_air',
    category: 'heat_exchangers',
    name: 'Condensador por Aire',
    description: 'Batería aleteada con ventiladores axiales para condensación por aire exterior.',
    defaultLabel: 'Condensador de Aire',
    defaultTagPrefix: 'COND-01',
    defaultModel: 'Guentner / Frimetal',
    dimensions: { width: 130, height: 120 },
    defaultSpecs: {
      capacityKw: 28.5,
      setpointTempC: 45.0,
      subcoolingK: 4.0,
    },
    ports: [
      { id: 'gas_in', name: 'Entrada Gas (HP)', shortCode: 'GAS-IN', kind: 'discharge', position: 'left', hint: 'Entrada de vapor caliente desde la descarga del compresor' },
      { id: 'liquid_out', name: 'Salida Líquido (HP)', shortCode: 'LIQ-OUT', kind: 'condensed', position: 'right', hint: 'Salida de refrigerante líquido condensado hacia recipiente' },
    ],
  },
  condenser_water_plate: {
    type: 'condenser_water_plate',
    category: 'heat_exchangers',
    name: 'Condensador de Placas (Agua)',
    description: 'Intercambiador de placas soldadas para condensación por agua de pozo o torre.',
    defaultLabel: 'Condensador Placas',
    defaultTagPrefix: 'COND-PLT',
    dimensions: { width: 125, height: 125 },
    defaultSpecs: {
      capacityKw: 35.0,
      setpointTempC: 38.0,
      subcoolingK: 5.0,
    },
    ports: [
      { id: 'ref_in', name: 'Gas Refrigerante', shortCode: 'GAS-IN', kind: 'discharge', position: 'top', hint: 'Entrada vapor caliente de refrigerante' },
      { id: 'ref_out', name: 'Líquido Refrigerante', shortCode: 'LIQ-OUT', kind: 'condensed', position: 'bottom', hint: 'Salida líquido condensado hacia recipiente' },
      { id: 'water_in', name: 'Agua Entrada', shortCode: 'H2O-IN', kind: 'water_in', position: 'left', hint: 'Entrada de agua fría de refrigeración (ej. 25°C)' },
      { id: 'water_out', name: 'Agua Salida', shortCode: 'H2O-OUT', kind: 'water_out', position: 'right', hint: 'Salida de agua caliente hacia torre o geotermia (ej. 32°C)' },
    ],
  },
  condenser_evaporative: {
    type: 'condenser_evaporative',
    category: 'heat_exchangers',
    name: 'Condensador Evaporativo',
    description: 'Torre de condensación con lluvia de agua pulverizada y tiro forzado de aire.',
    defaultLabel: 'Condensador Evap.',
    defaultTagPrefix: 'COND-EVP',
    dimensions: { width: 130, height: 130 },
    defaultSpecs: {
      capacityKw: 80.0,
      setpointTempC: 32.0,
    },
    ports: [
      { id: 'gas_in', name: 'Entrada Gas (HP)', shortCode: 'GAS-IN', kind: 'discharge', position: 'left', hint: 'Entrada de vapor caliente desde la descarga' },
      { id: 'liquid_out', name: 'Salida Líquido (HP)', shortCode: 'LIQ-OUT', kind: 'condensed', position: 'right', hint: 'Salida de líquido condensado hacia el recipiente' },
    ],
  },
  gas_cooler_co2: {
    type: 'gas_cooler_co2',
    category: 'heat_exchangers',
    name: 'Gas Cooler Transcrítico CO₂',
    description: 'Intercambiador de muy alta presión (120 bar) para enfriar el gas supercrítico de CO₂ (R744).',
    defaultLabel: 'Gas Cooler CO₂',
    defaultTagPrefix: 'GC-CO2',
    dimensions: { width: 130, height: 120 },
    defaultSpecs: {
      capacityKw: 45.0,
      pressureOutBar: 90.0,
      tempOutC: 32.0,
    },
    ports: [
      { id: 'gas_in', name: 'Gas Supercrítico (HP)', shortCode: 'GAS-IN', kind: 'discharge', position: 'left', hint: 'Entrada de gas de CO₂ supercrítico a 90-110 bar y 85-120°C' },
      { id: 'gas_out', name: 'Gas Enfriado Out', shortCode: 'GAS-OUT', kind: 'condensed', position: 'right', hint: 'Salida de gas enfriado hacia la válvula de alta presión (HPV)' },
    ],
  },
  evaporator_dx_air: {
    type: 'evaporator_dx_air',
    category: 'heat_exchangers',
    name: 'Evaporador DX por Aire',
    description: 'Evaporador de expansión directa aleteado con ventiladores para cámaras frigoríficas.',
    defaultLabel: 'Evaporador DX',
    defaultTagPrefix: 'EVAP-01',
    defaultModel: 'Alfa Laval / Lu-Ve',
    dimensions: { width: 130, height: 120 },
    defaultSpecs: {
      capacityKw: 18.0,
      setpointTempC: -5.0,
      superheatK: 6.0,
    },
    ports: [
      { id: 'liquid_in', name: 'Entrada Bifásica (LP)', shortCode: 'EXP-IN', kind: 'expansion_out', position: 'left', hint: 'Entrada de mezcla bifásica fría desde la válvula de expansión' },
      { id: 'gas_out', name: 'Salida Vapor (LP)', shortCode: 'VAP-OUT', kind: 'evaporated', position: 'right', hint: 'Salida de vapor recalentado hacia la aspiración del compresor' },
    ],
  },
  evaporator_plate_chiller: {
    type: 'evaporator_plate_chiller',
    category: 'heat_exchangers',
    name: 'Evaporador de Placas (Enfriadora)',
    description: 'Evaporador de placas soldadas para enfriamiento de agua o salmuera a 7°C.',
    defaultLabel: 'Evaporador Placas',
    defaultTagPrefix: 'EVAP-PLT',
    dimensions: { width: 125, height: 125 },
    defaultSpecs: {
      capacityKw: 30.0,
      setpointTempC: 3.0,
      superheatK: 5.0,
    },
    ports: [
      { id: 'ref_in', name: 'Entrada Refrigerante', shortCode: 'REF-IN', kind: 'expansion_out', position: 'bottom', hint: 'Entrada de refrigerante desde válvula de expansión' },
      { id: 'ref_out', name: 'Salida Vapor Seco', shortCode: 'REF-OUT', kind: 'evaporated', position: 'top', hint: 'Salida de vapor frío hacia la aspiración' },
      { id: 'water_in', name: 'Entrada Agua Retorno', shortCode: 'H2O-IN', kind: 'water_in', position: 'left', hint: 'Entrada de agua retornada del edificio (ej. 12°C)' },
      { id: 'water_out', name: 'Salida Agua Fría', shortCode: 'H2O-OUT', kind: 'water_out', position: 'right', hint: 'Salida de agua enfriada hacia fan-coils (ej. 7°C)' },
    ],
  },
  evaporator_flooded: {
    type: 'evaporator_flooded',
    category: 'heat_exchangers',
    name: 'Evaporador Inundado',
    description: 'Evaporador de carcasa inundado donde los tubos están completamente sumergidos en refrigerante.',
    defaultLabel: 'Evaporador Inundado',
    defaultTagPrefix: 'EVAP-FLD',
    dimensions: { width: 135, height: 125 },
    defaultSpecs: {
      capacityKw: 100.0,
      setpointTempC: -15.0,
    },
    ports: [
      { id: 'liquid_in', name: 'Alimentación Líquido', shortCode: 'LIQ-IN', kind: 'expansion_out', position: 'bottom', hint: 'Entrada de refrigerante líquido desde la bomba o flotador' },
      { id: 'gas_out', name: 'Aspiración Seca', shortCode: 'ASP-OUT', kind: 'evaporated', position: 'top', hint: 'Salida de vapor libre de gotas hacia el compresor' },
    ],
  },
  heat_exchanger_slhx: {
    type: 'heat_exchanger_slhx',
    category: 'heat_exchangers',
    name: 'Intercambiador Líquido-Aspiración (IHX)',
    description: 'Subenfría el líquido de alta presión con el vapor frío de aspiración para ganar eficiencia.',
    defaultLabel: 'IHX Líquido-Gas',
    defaultTagPrefix: 'HX-IHX',
    dimensions: { width: 125, height: 115 },
    defaultSpecs: {
      subcoolingK: 8.0,
      superheatK: 10.0,
    },
    ports: [
      { id: 'liq_in', name: 'Líquido Entrada (HP)', shortCode: 'LIQ-IN', kind: 'condensed', position: 'top', hint: 'Entrada de líquido caliente desde el condensador / recipiente' },
      { id: 'liq_out', name: 'Líquido Subenfriado', shortCode: 'LIQ-OUT', kind: 'subcooled', position: 'bottom', hint: 'Salida de líquido altamente subenfriado hacia la TXV' },
      { id: 'gas_in', name: 'Vapor Frío Entrada', shortCode: 'GAS-IN', kind: 'evaporated', position: 'left', hint: 'Entrada de vapor frío procedente del evaporador' },
      { id: 'gas_out', name: 'Vapor Recalentado Out', shortCode: 'GAS-OUT', kind: 'suction', position: 'right', hint: 'Salida de vapor sobrecalentado seco al compresor' },
    ],
  },
  desuperheater: {
    type: 'desuperheater',
    category: 'heat_exchangers',
    name: 'Desrecalentador / Recuperador Calor',
    description: 'Aprovecha el calor residual sensible de la descarga para precalentar ACS.',
    defaultLabel: 'Desrecalentador',
    defaultTagPrefix: 'HX-REC',
    dimensions: { width: 120, height: 110 },
    defaultSpecs: {
      capacityKw: 12.0,
    },
    ports: [
      { id: 'gas_in', name: 'Entrada Descarga HP', shortCode: 'GAS-IN', kind: 'discharge', position: 'left', hint: 'Entrada directa del gas caliente de compresión' },
      { id: 'gas_out', name: 'Salida Gas al Cond', shortCode: 'GAS-OUT', kind: 'discharge', position: 'right', hint: 'Salida de gas desrecalentado hacia el condensador principal' },
      { id: 'water_in', name: 'Agua Fría ACS', shortCode: 'ACS-IN', kind: 'water_in', position: 'bottom', hint: 'Entrada de agua de red (ej. 15°C)' },
      { id: 'water_out', name: 'Agua Caliente ACS', shortCode: 'ACS-OUT', kind: 'water_out', position: 'top', hint: 'Salida de agua precalentada (ej. 55°C)' },
    ],
  },

  // --- EXPANSION & REGULACION ---
  expansion_valve_txv: {
    type: 'expansion_valve_txv',
    category: 'expansion',
    name: 'Válvula Expansión Termostática (TXV)',
    description: 'Válvula termostática con bulbo sensor y toma de compensación externa de presión.',
    defaultLabel: 'Válvula TXV',
    defaultTagPrefix: 'TXV-01',
    defaultModel: 'Danfoss TE2 / T2',
    dimensions: { width: 110, height: 110 },
    defaultSpecs: {
      superheatK: 5.0,
      capacityKw: 14.5,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido HP', shortCode: 'LIQ-IN', kind: 'subcooled', position: 'left', hint: 'Entrada de líquido subenfriado a alta presión' },
      { id: 'outlet', name: 'Salida Bifásica LP', shortCode: 'EXP-OUT', kind: 'expansion_out', position: 'right', hint: 'Salida de refrigerante atomizado a baja presión hacia evaporador' },
      { id: 'equalization', name: 'Compensación Externa', shortCode: 'IGU', kind: 'equalization', position: 'bottom', hint: 'Tubo fino conectado a la salida del evaporador para compensar caída de presión' },
      { id: 'bulb', name: 'Bulbo Termostático', shortCode: 'BULB', kind: 'bulb', position: 'top', hint: 'Bulbo fijado al tubo de aspiración para censar el recalentamiento' },
    ],
  },
  expansion_valve_eev: {
    type: 'expansion_valve_eev',
    category: 'expansion',
    name: 'Válvula Expansión Electrónica (EEV)',
    description: 'Válvula paso a paso motorizada para control milimétrico de recalentamiento.',
    defaultLabel: 'Válvula EEV',
    defaultTagPrefix: 'EEV-01',
    defaultModel: 'Carel E2V / Danfoss ETS',
    dimensions: { width: 110, height: 110 },
    defaultSpecs: {
      openingPercent: 65,
      superheatK: 4.0,
      capacityKw: 25.0,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'LIQ-IN', kind: 'subcooled', position: 'left', hint: 'Entrada de líquido a alta presión' },
      { id: 'outlet', name: 'Salida Expansión', shortCode: 'EXP-OUT', kind: 'expansion_out', position: 'right', hint: 'Salida dosificada a baja presión hacia el evaporador' },
    ],
  },
  capillary_tube: {
    type: 'capillary_tube',
    category: 'expansion',
    name: 'Tubo Capilar',
    description: 'Tubo de cobre de pequeño diámetro para expansión por pérdida de carga fija.',
    defaultLabel: 'Tubo Capilar',
    defaultTagPrefix: 'CAP-01',
    dimensions: { width: 100, height: 75 },
    defaultSpecs: {
      capacityKw: 1.2,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'ENT', kind: 'subcooled', position: 'left', hint: 'Entrada desde el filtro deshidratador' },
      { id: 'outlet', name: 'Salida Evaporador', shortCode: 'SAL', kind: 'expansion_out', position: 'right', hint: 'Salida hacia el inicio del evaporador' },
    ],
  },
  float_valve: {
    type: 'float_valve',
    category: 'expansion',
    name: 'Válvula de Flotador',
    description: 'Regula el nivel de refrigerante líquido en sistemas inundados.',
    defaultLabel: 'Válvula Flotador',
    defaultTagPrefix: 'FLT-01',
    dimensions: { width: 105, height: 105 },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'IN', kind: 'subcooled', position: 'left', hint: 'Entrada de líquido' },
      { id: 'outlet', name: 'Salida Regulada', shortCode: 'OUT', kind: 'expansion_out', position: 'right', hint: 'Salida controlada por nivel de boya' },
    ],
  },
  regulator_epr_kvp: {
    type: 'regulator_epr_kvp',
    category: 'expansion',
    name: 'Regulador Presión Evaporación (KVP)',
    description: 'Impide que la presión del evaporador caiga por debajo de un valor prefijado.',
    defaultLabel: 'Regulador KVP',
    defaultTagPrefix: 'REG-KVP',
    dimensions: { width: 105, height: 105 },
    defaultSpecs: {
      setpointBar: 3.2,
    },
    ports: [
      { id: 'inlet', name: 'Entrada desde Evap', shortCode: 'EVAP', kind: 'evaporated', position: 'left', hint: 'Conexión a la salida del evaporador' },
      { id: 'outlet', name: 'Salida al Compresor', shortCode: 'COMP', kind: 'suction', position: 'right', hint: 'Conexión hacia la línea de aspiración general' },
    ],
  },
  regulator_cpr_kvl: {
    type: 'regulator_cpr_kvl',
    category: 'expansion',
    name: 'Regulador Presión Cárter (KVL)',
    description: 'Protege el motor del compresor limitando la presión máxima de succión en el arranque.',
    defaultLabel: 'Regulador KVL',
    defaultTagPrefix: 'REG-KVL',
    dimensions: { width: 105, height: 105 },
    defaultSpecs: {
      setpointBar: 4.5,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Línea Succión', shortCode: 'SUC-IN', kind: 'evaporated', position: 'left', hint: 'Entrada desde los evaporadores' },
      { id: 'outlet', name: 'Salida al Cárter', shortCode: 'CMP-IN', kind: 'suction', position: 'right', hint: 'Salida regulada directa a la aspiración del compresor' },
    ],
  },
  regulator_kvr: {
    type: 'regulator_kvr',
    category: 'expansion',
    name: 'Regulador Condensación (KVR)',
    description: 'Mantiene una presión de condensación mínima suficiente durante el invierno.',
    defaultLabel: 'Regulador KVR',
    defaultTagPrefix: 'REG-KVR',
    dimensions: { width: 105, height: 105 },
    defaultSpecs: {
      setpointBar: 12.0,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Condensador', shortCode: 'COND', kind: 'condensed', position: 'left', hint: 'Entrada desde la salida del condensador' },
      { id: 'outlet', name: 'Salida al Recipiente', shortCode: 'REC', kind: 'subcooled', position: 'right', hint: 'Salida hacia el depósito de líquido' },
    ],
  },

  // --- RECIPIENTES & ACEITE ---
  liquid_receiver_vertical: {
    type: 'liquid_receiver_vertical',
    category: 'vessels',
    name: 'Recipiente de Líquido Vertical',
    description: 'Depósito vertical para almacenar la reserva de líquido refrigerante condensado.',
    defaultLabel: 'Recipiente Líquido',
    defaultTagPrefix: 'REC-01',
    dimensions: { width: 110, height: 135 },
    defaultSpecs: {
      volumeL: 25.0,
      pressureOutBar: 14.5,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Condensado', shortCode: 'COND-IN', kind: 'condensed', position: 'top', hint: 'Entrada superior de líquido procedente del condensador' },
      { id: 'outlet', name: 'Salida Líquido a TXV', shortCode: 'LIQ-OUT', kind: 'subcooled', position: 'bottom', hint: 'Salida inferior de columna continua de líquido hacia filtro y TXV' },
    ],
  },
  liquid_receiver_horizontal: {
    type: 'liquid_receiver_horizontal',
    category: 'vessels',
    name: 'Recipiente Líquido Horizontal',
    description: 'Depósito horizontal de alta capacidad para centrales frigoríficas industriales.',
    defaultLabel: 'Recipiente Horiz.',
    defaultTagPrefix: 'REC-HOR',
    dimensions: { width: 140, height: 105 },
    defaultSpecs: {
      volumeL: 120.0,
    },
    ports: [
      { id: 'inlet', name: 'Entrada Condensado', shortCode: 'IN', kind: 'condensed', position: 'top', hint: 'Entrada superior desde condensador' },
      { id: 'outlet', name: 'Salida Líquido', shortCode: 'OUT', kind: 'subcooled', position: 'bottom', hint: 'Salida hacia línea de líquido de la central' },
    ],
  },
  suction_accumulator: {
    type: 'suction_accumulator',
    category: 'vessels',
    name: 'Acumulador de Succión',
    description: 'Impide que gotas de refrigerante líquido no evaporado alcancen los cilindros del compresor.',
    defaultLabel: 'Acumulador Succión',
    defaultTagPrefix: 'ACC-01',
    dimensions: { width: 110, height: 135 },
    defaultSpecs: {
      volumeL: 12.0,
    },
    ports: [
      { id: 'inlet', name: 'Entrada desde Evap', shortCode: 'EVAP-IN', kind: 'evaporated', position: 'top', hint: 'Entrada de gas húmedo procedente de la línea de evaporación' },
      { id: 'outlet', name: 'Salida a Compresor', shortCode: 'CMP-OUT', kind: 'suction', position: 'right', hint: 'Salida superior de vapor 100% seco hacia el compresor' },
    ],
  },
  oil_separator: {
    type: 'oil_separator',
    category: 'vessels',
    name: 'Separador de Aceite',
    description: 'Separa el lubricante arrastrado en la descarga y lo retorna de forma continua al cárter.',
    defaultLabel: 'Separador Aceite',
    defaultTagPrefix: 'SEP-OIL',
    dimensions: { width: 110, height: 130 },
    ports: [
      { id: 'gas_in', name: 'Entrada Descarga HP', shortCode: 'DESC-IN', kind: 'discharge', position: 'left', hint: 'Entrada de mezcla gas caliente + microgotas de aceite' },
      { id: 'gas_out', name: 'Gas al Condensador', shortCode: 'GAS-OUT', kind: 'discharge', position: 'right', hint: 'Gas limpio de aceite hacia el condensador' },
      { id: 'oil_return', name: 'Retorno Aceite Cárter', shortCode: 'OIL-RET', kind: 'oil', position: 'bottom', hint: 'Tubo de retorno de aceite regulado por flotador interno al cárter' },
    ],
  },
  oil_reservoir: {
    type: 'oil_reservoir',
    category: 'vessels',
    name: 'Depósito Colector Aceite',
    description: 'Almacén centralizado de aceite para alimentación regulada a múltiples compresores.',
    defaultLabel: 'Depósito Aceite',
    defaultTagPrefix: 'RES-OIL',
    dimensions: { width: 110, height: 125 },
    ports: [
      { id: 'oil_in', name: 'Entrada Separadores', shortCode: 'OIL-IN', kind: 'oil', position: 'top', hint: 'Entrada de aceite recogido de los separadores' },
      { id: 'oil_out', name: 'Salida a Reguladores', shortCode: 'OIL-OUT', kind: 'oil', position: 'bottom', hint: 'Salida a reguladores de nivel electrónicos de cada compresor' },
    ],
  },
  flash_tank_economizer: {
    type: 'flash_tank_economizer',
    category: 'vessels',
    name: 'Botella Flash Economizador',
    description: 'Vaso de expansión intermedia que genera vapor flash para inyección EVI y subenfría el líquido.',
    defaultLabel: 'Botella Flash',
    defaultTagPrefix: 'FLSH-01',
    dimensions: { width: 120, height: 135 },
    defaultSpecs: {
      pressureOutBar: 6.5,
      tempOutC: 12.0,
      volumeL: 15.0,
    },
    ports: [
      { id: 'liquid_in', name: 'Entrada Expansión 1', shortCode: 'EXP-1', kind: 'expansion_out', position: 'top', hint: 'Entrada de líquido tras primera caída de presión' },
      { id: 'flash_gas', name: 'Vapor Flash a Compresor', shortCode: 'EVI-GAS', kind: 'intermediate', position: 'right', hint: 'Vapor saturado intermedio hacia el puerto EVI del compresor' },
      { id: 'liquid_out', name: 'Líquido Subenfriado a TXV', shortCode: 'LIQ-SUB', kind: 'subcooled', position: 'bottom', hint: 'Líquido frío subenfriado hacia la válvula de evaporación' },
    ],
  },
  filter_drier: {
    type: 'filter_drier',
    category: 'accessories',
    name: 'Filtro Deshidratador',
    description: 'Filtro de tamiz molecular para atrapar partículas sólidas y absorber trazas de agua ácida.',
    defaultLabel: 'Filtro Deshidratador',
    defaultTagPrefix: 'FLT-01',
    defaultModel: 'Danfoss DML 163',
    dimensions: { width: 105, height: 75 },
    ports: [
      { id: 'inlet', name: 'Entrada Líquido', shortCode: 'ENT', kind: 'subcooled', position: 'left', hint: 'Entrada desde el recipiente de líquido' },
      { id: 'outlet', name: 'Salida Líquido', shortCode: 'SAL', kind: 'subcooled', position: 'right', hint: 'Salida limpia y seca hacia el visor y la TXV' },
    ],
  },
  sight_glass: {
    type: 'sight_glass',
    category: 'accessories',
    name: 'Visor Líquido / Humedad',
    description: 'Mirilla transparente con corona de sales indicadoras de humedad (Verde = Seco, Amarillo = Húmedo).',
    defaultLabel: 'Visor Líquido',
    defaultTagPrefix: 'SGT-01',
    dimensions: { width: 95, height: 75 },
    ports: [
      { id: 'inlet', name: 'Entrada', shortCode: 'ENT', kind: 'subcooled', position: 'left', hint: 'Entrada de línea de líquido' },
      { id: 'outlet', name: 'Salida', shortCode: 'SAL', kind: 'subcooled', position: 'right', hint: 'Salida hacia válvula de expansión' },
    ],
  },

  // --- VALVULAS & SEGURIDAD ---
  four_way_reversing_valve: {
    type: 'four_way_reversing_valve',
    category: 'valves',
    name: 'Válvula Inversora 4 Vías',
    description: 'Permite invertir el ciclo en bombas de calor para alternar entre modo Frío y modo Calor.',
    defaultLabel: 'Válvula 4 Vías',
    defaultTagPrefix: '4WY-01',
    dimensions: { width: 125, height: 125 },
    ports: [
      { id: 'discharge_in', name: 'Descarga Compresor', shortCode: 'DESC', kind: 'discharge', position: 'top', hint: 'Conexión a la descarga de gas caliente del compresor' },
      { id: 'suction_out', name: 'Aspiración Compresor', shortCode: 'ASP', kind: 'suction', position: 'bottom', hint: 'Conexión a la aspiración permanente del compresor' },
      { id: 'outdoor_coil', name: 'Batería Exterior', shortCode: 'EXT', kind: 'generic', position: 'left', hint: 'Conexión a la batería exterior (Condensador en verano / Evaporador en invierno)' },
      { id: 'indoor_coil', name: 'Batería Interior', shortCode: 'INT', kind: 'generic', position: 'right', hint: 'Conexión a la batería interior (Evaporador en verano / Condensador en invierno)' },
    ],
  },
  solenoid_valve: {
    type: 'solenoid_valve',
    category: 'valves',
    name: 'Válvula Solenoide (NC)',
    description: 'Válvula electromagnética on/off para corte de líquido en parada o bombeo de vaciado (pump down).',
    defaultLabel: 'Válvula Solenoide',
    defaultTagPrefix: 'SOL-01',
    dimensions: { width: 105, height: 100 },
    defaultSpecs: {
      voltageV: 230,
    },
    ports: [
      { id: 'inlet', name: 'Entrada', shortCode: 'IN', kind: 'generic', position: 'left', hint: 'Entrada de refrigerante' },
      { id: 'outlet', name: 'Salida', shortCode: 'OUT', kind: 'generic', position: 'right', hint: 'Salida habilitada al energizar la bobina eléctrica' },
    ],
  },
  check_valve: {
    type: 'check_valve',
    category: 'valves',
    name: 'Válvula Retención (Check)',
    description: 'Permite el paso en un único sentido impidiendo retornos indebidos de refrigerante.',
    defaultLabel: 'Válvula Check',
    defaultTagPrefix: 'CHK-01',
    dimensions: { width: 100, height: 75 },
    ports: [
      { id: 'inlet', name: 'Entrada Flujo', shortCode: 'IN', kind: 'generic', position: 'left', hint: 'Sentido permitido del refrigerante' },
      { id: 'outlet', name: 'Salida Flujo', shortCode: 'OUT', kind: 'generic', position: 'right', hint: 'Salida (bloquea el retorno en sentido contrario)' },
    ],
  },
  safety_relief_valve: {
    type: 'safety_relief_valve',
    category: 'valves',
    name: 'Válvula Seguridad Alivio',
    description: 'Válvula mecánica tarada para descargar presión a la atmósfera en caso de incendio o sobrepresión.',
    defaultLabel: 'Válvula Seguridad',
    defaultTagPrefix: 'PRV-01',
    dimensions: { width: 95, height: 100 },
    defaultSpecs: {
      setpointBar: 28.0,
    },
    ports: [
      { id: 'inlet', name: 'Toma Recipiente', shortCode: 'REC', kind: 'generic', position: 'bottom', hint: 'Conexión a la parte superior del recipiente de líquido' },
      { id: 'vent', name: 'Escape Seguridad', shortCode: 'VENT', kind: 'generic', position: 'top', hint: 'Tubo de venteo hacia el exterior del edificio' },
    ],
  },
  hot_gas_bypass_valve: {
    type: 'hot_gas_bypass_valve',
    category: 'valves',
    name: 'Válvula Bypass Gas Caliente',
    description: 'Inyecta gas de descarga caliente en la baja presión para modular capacidad y evitar congelación.',
    defaultLabel: 'Bypass Gas Caliente',
    defaultTagPrefix: 'HGBP-01',
    dimensions: { width: 110, height: 110 },
    defaultSpecs: {
      setpointBar: 2.0,
    },
    ports: [
      { id: 'hp_in', name: 'Entrada Descarga HP', shortCode: 'HP-IN', kind: 'discharge', position: 'left', hint: 'Toma de gas caliente directo desde la descarga' },
      { id: 'lp_out', name: 'Salida Inyección LP', shortCode: 'LP-OUT', kind: 'hot_gas_bypass', position: 'right', hint: 'Inyección a la entrada del evaporador o a la aspiración' },
      { id: 'equalization', name: 'Toma Presión', shortCode: 'IGU', kind: 'equalization', position: 'bottom', hint: 'Línea de presión de referencia' },
    ],
  },
  ball_service_valve: {
    type: 'ball_service_valve',
    category: 'valves',
    name: 'Válvula de Bola / Servicio',
    description: 'Válvula de aislamiento manual de 1/4 de vuelta para mantenimiento y corte de tramos.',
    defaultLabel: 'Válvula Bola',
    defaultTagPrefix: 'VLV-01',
    dimensions: { width: 95, height: 85 },
    ports: [
      { id: 'inlet', name: 'Entrada', shortCode: 'IN', kind: 'generic', position: 'left', hint: 'Entrada de tubería' },
      { id: 'outlet', name: 'Salida', shortCode: 'OUT', kind: 'generic', position: 'right', hint: 'Salida de tubería' },
    ],
  },

  // --- INSTRUMENTACION & SENSORES ---
  gauge_pressure_hp: {
    type: 'gauge_pressure_hp',
    category: 'instruments',
    name: 'Manómetro Alta Presión (HP)',
    description: 'Manómetro dial rojo para lectura de presión de descarga y condensación.',
    defaultLabel: 'Manómetro HP',
    defaultTagPrefix: 'PI-HP',
    dimensions: { width: 95, height: 100 },
    defaultSpecs: {
      measuredValue: 14.8,
      measuredUnit: 'bar',
    },
    ports: [
      { id: 'inlet', name: 'Toma Presión', shortCode: 'HP', kind: 'discharge', position: 'bottom', hint: 'Toma de manómetro en línea de descarga o condensador' },
    ],
  },
  gauge_pressure_lp: {
    type: 'gauge_pressure_lp',
    category: 'instruments',
    name: 'Manómetro Baja Presión (LP)',
    description: 'Manómetro dial azul para lectura de presión de aspiración y evaporación.',
    defaultLabel: 'Manómetro LP',
    defaultTagPrefix: 'PI-LP',
    dimensions: { width: 95, height: 100 },
    defaultSpecs: {
      measuredValue: 2.1,
      measuredUnit: 'bar',
    },
    ports: [
      { id: 'inlet', name: 'Toma Presión', shortCode: 'LP', kind: 'suction', position: 'bottom', hint: 'Toma de manómetro en línea de aspiración o evaporador' },
    ],
  },
  sensor_temperature: {
    type: 'sensor_temperature',
    category: 'instruments',
    name: 'Sonda Temperatura (NTC/PT100)',
    description: 'Sensor térmico de contacto para medición de temperaturas en tuberías.',
    defaultLabel: 'Sonda Temp.',
    defaultTagPrefix: 'TI-01',
    dimensions: { width: 90, height: 90 },
    defaultSpecs: {
      measuredValue: -5.5,
      measuredUnit: '°C',
    },
    ports: [
      { id: 'inlet', name: 'Sonda Contacto', shortCode: 'T', kind: 'generic', position: 'bottom', hint: 'Fijación por abrazadera al tubo para medir temperatura superficial' },
    ],
  },
  pressure_switch: {
    type: 'pressure_switch',
    category: 'instruments',
    name: 'Presostato Dual Alta / Baja',
    description: 'Dispositivo de seguridad que corta la maniobra eléctrica ante sobrepresión o falta de gas.',
    defaultLabel: 'Presostato Dual',
    defaultTagPrefix: 'PS-01',
    dimensions: { width: 110, height: 105 },
    defaultSpecs: {
      setpointBar: 18.0,
    },
    ports: [
      { id: 'hp_tap', name: 'Toma Alta (HP)', shortCode: 'HP', kind: 'discharge', position: 'right', hint: 'Capilar conectado a la descarga' },
      { id: 'lp_tap', name: 'Toma Baja (LP)', shortCode: 'LP', kind: 'suction', position: 'left', hint: 'Capilar conectado a la aspiración' },
    ],
  },
  flow_meter: {
    type: 'flow_meter',
    category: 'instruments',
    name: 'Caudalímetro Másico',
    description: 'Medidor en línea de caudal másico [kg/s] o volumétrico [m³/h] de refrigerante.',
    defaultLabel: 'Caudalímetro',
    defaultTagPrefix: 'FI-01',
    dimensions: { width: 105, height: 85 },
    defaultSpecs: {
      measuredValue: 0.045,
      measuredUnit: 'kg/s',
    },
    ports: [
      { id: 'inlet', name: 'Entrada', shortCode: 'IN', kind: 'generic', position: 'left', hint: 'Entrada de flujo' },
      { id: 'outlet', name: 'Salida', shortCode: 'OUT', kind: 'generic', position: 'right', hint: 'Salida de flujo' },
    ],
  },
  power_meter: {
    type: 'power_meter',
    category: 'instruments',
    name: 'Vatímetro / Analizador Red',
    description: 'Medidor de potencia eléctrica activa [kW], consumo energético [kWh] y factor de potencia.',
    defaultLabel: 'Vatímetro',
    defaultTagPrefix: 'EI-01',
    dimensions: { width: 100, height: 100 },
    defaultSpecs: {
      measuredValue: 8.2,
      measuredUnit: 'kW',
    },
    ports: [
      { id: 'comp_link', name: 'Alimentación Motor', shortCode: 'PWR', kind: 'generic', position: 'bottom', hint: 'Conexión a cuadro de maniobra del compresor' },
    ],
  },
};

export const COMPONENT_CATEGORIES: { id: SchematicComponentCategory; label: string; icon: string }[] = [
  { id: 'compressors', label: 'Compresores & Bombas', icon: 'Zap' },
  { id: 'heat_exchangers', label: 'Intercambiadores de Calor', icon: 'Flame' },
  { id: 'expansion', label: 'Expansión & Regulación', icon: 'Gauge' },
  { id: 'vessels', label: 'Recipientes & Aceite', icon: 'Database' },
  { id: 'valves', label: 'Válvulas & Seguridad', icon: 'Sliders' },
  { id: 'accessories', label: 'Filtros & Visores', icon: 'Eye' },
  { id: 'instruments', label: 'Instrumentación & Sensores', icon: 'Activity' },
];
